### ISSUE TITLE
Gem is changing cookie name on production working fine on local

### ISSUE THREAD

**Issue by imtiazwazir** [thoughtbot/clearance#1003]
Config:

`
Clearance.configure do |config|
  config.allow_sign_up = false
  config.cookie_domain = nil
  config.routes = true
  config.mailer_sender = "reply@MYDOMAIN.com"
  config.redirect_url = "/admin"
  config.rotate_csrf_on_sign_in = true
  config.secure_cookie = false
end
`

<img width="338" alt="Screenshot 2024-02-05 at 5 59 48 PM" src="https://github.com/thoughtbot/clearance/assets/1964969/c437d9ac-f6c9-4c5c-9b73-98bbbfee2ce1">

All the gem and rails version is up to date.

**Comment by dorianmarie** [comment]
Could you provide a sample app to reproduce the issue?

**Comment by imtiazwazir** [comment]
Thanks @dorianmarie, I came to one conclusion since its a reverse proxy maybe the server is changing it some where, I will test it with devise gem and let you know

my app is in a private repo if you want I can send to app link and login info in PM

**Comment by imtiazwazir** [comment]
Devise gem working fine, something wrong with the redirect session generating cookie in array from.
