### ISSUE TITLE
Query params removed after update from version 2.8.0 to 2.9.1

### ISSUE THREAD

**Issue by marcelorxaviers** [thoughtbot/clearance#1040]
**Description:**

After updating the gem from version 2.8.0 to 2.9.1, I encountered an issue where certain query parameters are no longer passed correctly. Specifically, the date parameter and other query parameters are missing from the params hash in GET requests, although they were present in version 2.8.0.

**Steps to Reproduce:**

1. Make a GET request to some_url with query parameters, using version 2.8.0:
```ruby
get some_url(something.id, date:, format: "csv", as: admin_user)
```

2. Check params.keys. The output is as expected:
```ruby
> params.keys
=> ["date", "controller", "action", "something_id", "format"]
```

3. Update the gem to version 2.9.1.
4. Make the same GET request with the identical parameters:
```ruby
get some_url(something.id, date:, format: "csv", as: admin_user)
```
5. Check params.keys again. This time, the date parameter (and all other query parameters) are missing:
```ruby
> params.keys
=> ["controller", "action", "something_id", "format"]
```

**Expected Behavior:**

The date and other query parameters should still be included in params.keys after updating to version 2.9.1.

**Actual Behavior:**

The date parameter (along with other query parameters) is no longer present in params.keys.

**Environment:**

Gem version: 2.9.1 (works as expected in 2.8.0)
Ruby version: 3.3.5
Rails version: 7.2.1.2 

**Additional Information:**
- I tested with version 2.9.0, and the issue seems to have been introduced there. Version 2.9.0 behaves the same as version 2.9.1, where the query parameters are missing, while version 2.8.0 works as expected.
- I tried passing other query parameters, and all of them are removed from params.keys in versions 2.9.0 and 2.9.1.

Has anyone else experienced this issue?

**Comment by karlentwistle** [comment]
> Has anyone else experienced this issue?

Thanks for posting this issue. I am also experiencing the same behaviour on 2.9.1

```ruby
visit film_path(film, as: user, cinema_id: cinema.id)
```

The `cinema_id` is being stripped out but works via

```ruby
visit film_path(film, as: user)
visit film_path(film, cinema_id: cinema.id)
```

However on 2.8.0

```ruby
visit film_path(film, as: user, cinema_id: cinema.id)
```

Works as expected

**Comment by karlentwistle** [comment]
Checking

```
gem 'clearance', github: 'thoughtbot/clearance', ref: '704ba2a029dd687b0af4e0ae45804c66f7e462cf'
gem 'clearance', github: 'thoughtbot/clearance', ref: '6bd5f5b26bd6ce3b5d438f33f30868abd29618c8'
gem 'clearance', github: 'thoughtbot/clearance', ref: '31d8d73638c71fb918eee463852b5eb42d5e5375'
gem 'clearance', github: 'thoughtbot/clearance', ref: '6bd5f5b26bd6ce3b5d438f33f30868abd29618c8'
gem 'clearance', github: 'thoughtbot/clearance', ref: '31d8d73638c71fb918eee463852b5eb42d5e5375'
gem 'clearance', github: 'thoughtbot/clearance', ref: '767c002bf15fe10327e3c50b2865a369938ad1b2'
gem 'clearance', github: 'thoughtbot/clearance', ref: '17654b88c16aa25af1c6d007775497ddd642f01c'
```

It appears that https://github.com/thoughtbot/clearance/commit/767c002bf15fe10327e3c50b2865a369938ad1b2 changed the previous behaviour

**Comment by karlentwistle** [comment]
On further investigation, it seems like this is the part of the commit that is responsible [lib/clearance/back_door.rb](https://github.com/thoughtbot/clearance/commit/767c002bf15fe10327e3c50b2865a369938ad1b2#diff-0b3f4620807c99e5dc827ab639ddc302ba29a2ae43a8c0e81e40262bc608908dR51-R57), interestingly:

Working

```ruby
# @api private
def sign_in_through_the_back_door(env)
  params = Rack::Utils.parse_query(env[Rack::QUERY_STRING])
  user_param = params.delete("as")

  if user_param.present?
    query_string = Rack::Utils.build_query(params)
    env[Rack::QUERY_STRING] = query_string
    user = find_user(user_param)
    env[:clearance].sign_in(user)
  end
end
```

Working

```ruby
# @api private
def sign_in_through_the_back_door(env)
  params = Rack::Utils.parse_query(env[Rack::QUERY_STRING])
  user_param = params.delete("as")

  if user_param.present?
    query_string = Rack::Utils.build_query(params)
    env[Rack::RACK_REQUEST_QUERY_STRING] = query_string
    user = find_user(user_param)
    env[:clearance].sign_in(user)
  end
end
```

But fails when both are used in conjunction

```ruby
# @api private
def sign_in_through_the_back_door(env)
  params = Rack::Utils.parse_query(env[Rack::QUERY_STRING])
  user_param = params.delete("as")

  if user_param.present?
    query_string = Rack::Utils.build_query(params)
    env[Rack::QUERY_STRING] = query_string
    env[Rack::RACK_REQUEST_QUERY_STRING] = query_string
    user = find_user(user_param)
    env[:clearance].sign_in(user)
  end
end
```

**Comment by Uaitt** [comment]
Facing the same issue here

**Comment by sej3506** [comment]
Sorry for the difficulties, folks -- Looking into this this week.

**Comment by rickychilcott** [comment]
Not sure if it helps, but there is some stuff in https://github.com/rack/rack/pull/2073/files that makes me think that there is another value (i.e., RACK_REQUEST_QUERY_HASH) that gets used when RACK_REQUEST_QUERY_STRING and QUERY_STRING are I the I same I. In this case, RACK_REQUEST_QUERY_HASH might be `nil` or `{}`, which would cause Rails `params` to not have the query parameters.

I didn't trace all the code to know if that's how it's currently working in Rack.
