### ISSUE TITLE
The action 'create' could not be found for UsersController

### ISSUE THREAD

**Issue by jarkelen** [thoughtbot/clearance#286]
I have used Clearance for a while now without problems, but now if I want to register a new user and fill in the registration form, after clicking the submit button, I receive the error: "The action 'create' could not be found for UsersController".

It seems it is not using the create method from the Clearance Users controller?
In the Application controller the first line is "include Clearance::Controller". Any help would be great!

Registration worked before without problems.

**Comment by surendhirans** [comment]
The action 'create' could not be found for PostsController.
im getting error in this. could please help me to solve this error.
