### ISSUE TITLE
How not to sign out same user on all other machines when a user signs out

### ISSUE THREAD

**Issue by sushengloong** [thoughtbot/clearance#325]
When a user signs out from a machine, other users using same username on different machines will also be signed out at the same time. This is the default behavior and I can see that this is done by resetting user's remember token.

However, I need other users to remain signed-in on their machines even after any of the users has signed out. Is there an option for me to override this behavior in `config/initializers/clearance.rb` or I should just monkey-patch the `Clearance::Session#sign_out` method? Thank you.

``` ruby
module Clearance
  class Session
    ... (omitted)

    def sign_out
      if signed_in?
        current_user.reset_remember_token!
      end

      @current_user = nil
      cookies.delete REMEMBER_TOKEN_COOKIE
    end

    ... (omitted)
  end
end
```

**Comment by gingerlime** [comment]
I know it's an old one, but I'm also curious about this one, and sadly the link to google groups doesn't work for me.

Is monkey-patching `sign_out` still the only way to achieve this? Is this something open for discussion / PRs ?

**Comment by croaky** [comment]
I'm not an active maintainer of this project anymore so can't speak to library changes but monkey-patching `sign_out` in the controller where you've mixed in `Clearance::Controller` or `Clearance::Authentication` should still work.

```ruby
def sign_out
  cookies.clear
end
```

That's heavy-handed but may work. The goal is to skip the `current_user.reset_remember_token!` portion of https://github.com/thoughtbot/clearance/blob/bff3aeb02a12e8ec9aa5658fee1d8bf9afe98e55/lib/clearance/session.rb#L80

**Comment by gingerlime** [comment]
Thanks @croaky 

From experimenting a bit I’m not sure it’s as simple.

I don’t want to clear all cookies, and deleting one cookie might require passing the options.

More important however, I want to also clear @current_user ?

So I think it does require monkey patching to have a more robust solution?

I’m just a bit surprised that all clearance users are happy with logging out having an effect on all devices (or many are monkey patching?)

**Comment by croaky** [comment]
Can't speak to the broader questions but a few other ideas to try:

```ruby
def sign_out
  request.env[:clearance] = Clearance::Session.new(request.env) # @current_user is nil on instantiation
  session[:return_to] = nil
  cookies.delete "remember_token"
end
```

**Comment by gingerlime** [comment]
That’s clever! thank you. I’ll give it a try tomorrow 👍
