### ISSUE TITLE
Mongoid Official Support

### ISSUE THREAD

**Issue by hartator** [thoughtbot/clearance#350]
Seems you have done a great work with clearance guys, thanks for that!

I wonder if you plan in giving a official support for Mongoid, I would love to see that coming. I've seen this issue https://github.com/thoughtbot/clearance/issues/55 but it seems that it's not yet implemented (Maybe I am wrong)

Anyway thanks again!

**Comment by ekremkaraca** [comment]
@croaky What about state of issue, will it be possible to combine clearance with mongoid?

**Comment by derekprior** [comment]
We cannot offer support for ORMs we do not ourselves use.
