### ISSUE TITLE
Don't validate user when updating password

### ISSUE THREAD

**Issue by derekprior** [thoughtbot/clearance#406]
When updating a users password, clearance [runs a full validation](https://github.com/thoughtbot/clearance/blob/master/lib/clearance/user.rb#L78). There are a number of reasons that a user may be invalid that are out of the scope of what clearance provides. Password resets should not be held up due to a new required field being added to user, for instance.

**Comment by mjankowski** [comment]
Resolved by https://github.com/thoughtbot/clearance/pull/521

**Comment by calebthompson** [comment]
I am relieved.
