### ISSUE TITLE
CSS styles for Clearance

### ISSUE THREAD

**Issue by croaky** [thoughtbot/clearance#438]
@frechg worked on extracting some code from a project that used Clearance:

https://github.com/frechg/clearance-styles

We have lots of projects that have styled Clearance and could pull styles from any of them. It'd be nice to not have to repeat this work on each new project.

**Comment by chug2k** [comment]
i'm late to the party here, but did a separate gem ever get made? hopefully on a Friday sometime last year?

**Comment by derekprior** [comment]
No, not to my knowledge.
