### ISSUE TITLE
Sign in page can be visited while signed in

### ISSUE THREAD

**Issue by gabrielecirulli** [thoughtbot/clearance#453]
Using the latest gem version of clearance, without any strange configuration and tweaks (except I generated the views and tweaked them), I can visit the sign in page while I'm already signed in.

The expected behavior would be being redirected to either the root path or a path of my liking if I try to visit that page when signed in.

Is this possible without having to override things?

**Comment by derekprior** [comment]
There's an argument to be made that this is just a bug and should be fixed. I can't think of any use case that this would totally destroy, so I think we should probably just fix it.

**Comment by gabrielecirulli** [comment]
I agree. The general consensus on the web is to "bounce" back users that are already signed in if they try to visit a page that is reserved for signed-out users. This issue is not necessarily a bug (it doesn't cause any problems), but it can definitely cause confusion and make an application not feel very solid to the user.

**Comment by derekprior** [comment]
Closed with #513, which will be in our next 1.x release (likely 1.7.1, possibly 1.8).
