### ISSUE TITLE
Clearance::xxxController.layout is reset when rails auto reloads classes

### ISSUE THREAD

**Issue by lenart** [thoughtbot/clearance#487]
It looks like overriding layouts at the bottom of initializer file causes weird behavior where sometimes the default application layout is used instead. It might be a good idea to be more specific in the [README.md](https://github.com/thoughtbot/clearance#overriding-layouts) where the overrides should be placed. I've now placed layout settings before `Clearance.configure` block and seems like things are now working.

**Comment by derekprior** [comment]
I haven't tried to reproduce this, but it does make sense. If the override is in the initializer then it will not get run if rails reloads the controller class.

But if you're editing the controller class which is causing it to be reloaded then could you override the layout in that class instead?

**Comment by derekprior** [comment]
Closing. Let me know if the suggested workaround doesn't work for you and I'll re-open.

**Comment by matoakley** [comment]
I am having the same problem as above but I have not overridden the Clearance controllers, therefore cannot set my layout in the controller. I can create a class to set the layout as a workaround but it's not an ideal solution.

**Comment by fagiani** [comment]
This problem still happens today. I've been able to work around it by issuing: `bin/spring stop`, and even it will say `Spring is not running` it fixed for me.

Hope it helps!

**Comment by damienbrz** [comment]
I had the same issue and moving
`Clearance::UsersController.layout "public"`
Before the block 
`Clearance.configure`
solved my problem

No idea why though...
