### ISSUE TITLE
before_filter is deprecated in 4.2

### ISSUE THREAD

**Issue by derekprior** [thoughtbot/clearance#519]
Rails 4.2 deprecates `before_filter` and `skip_before_filter`. We can't switch to `before_action` and `skip_before_action` in 1.x because we support Rails 3.

So... we likely need to define a method on Clearance::BaseController that can be called instead and dispatches the proper method based on whats defined.

**Comment by jferris** [comment]
Can you do something like:

``` ruby
if defined?(:skip_before_action)
  skip_before_action :require_login
else
  skip_before_filter :require_login
end
```

**Comment by jferris** [comment]
Also, it might be worth dropping support for Rails 3 soon (or at least deprecating it). There have been three minor releases (4.0, 4.1, 4.2) since Rails 3, so people have had plenty of time to switch (since June, 2013 according to rubygems.org).

**Comment by derekprior** [comment]
> Can you do something like:

Yes. But I need to do that 6 different times. So I was going to wrap that in a method on Clearance::BaseController

**Comment by jferris** [comment]
> Yes. But I need to do that 6 different times. So I was going to wrap that in a method on Clearance::BaseController

Sounds good to me.

**Comment by derekprior** [comment]
> Also, it might be worth dropping support for Rails 3 soon (or at least deprecating it). There have been three minor releases (4.0, 4.1, 4.2) since Rails 3, so people have had plenty of time to switch (since June, 2013 according to rubygems.org).

Yup. The problem is I'm in the midst of one bunch of deprecations already and I'd like to get those done before bumping the major version. 2.0 will clear those deprecations and also require Ruby 2.1+ and Rails 4.2+

**Comment by derekprior** [comment]
4.2 might be a bit strict. Might have to let in 4.1 or even 4.0

**Comment by derekprior** [comment]
I'm not sure we need to do this, actually. The `_filter` methods are not deprecated they are just no longer documented. The release notes say:

> If your application currently depends on these methods, you should use the replacement *_action methods instead. These methods will be deprecated in the future and will eventually be removed from Rails.

I feel like we should be good until Rails 5, at which point we'll hopefully have a new major version of clearance that supports Rails 4+ (and 5).

**Comment by derekprior** [comment]
Closing as I don't think we should do anything yet. We should just switch over to `_action` in Clearance 2
