### ISSUE TITLE
Add documentation on which databases/ORMs are supported

### ISSUE THREAD

**Issue by andrewhavens** [thoughtbot/clearance#545]
I didn't see this mentioned in the README so I'm reporting this as a bug... Is clearance only compatible with ActiveRecord and AR compatible databases? Or are additional databases supported? I'm interested in whether or not MongoDB (Mongoid, MongoMapper) and Neo4j (neo4j.rb, neography) are or could be supported.

**Comment by derekprior** [comment]
It's likely Mongoid could be supported (minus migrations) with the right User model. I have no idea about Neo4j. This gem is definitely focused on ActiveRecord. That said, I am currently working on documentation when I get the time, so hopefully soon there will be documentation on what `Clearance::User` requires.

I don't want to document support for anything other than active record unless that support is tested and maintained, but better docs on the interfaces required would at least give people a starting point.

**Comment by derekprior** [comment]
Documentation is coming along slowly. I don't forsee us ever officially supporting anything other than ActiveRecord so I'm going to close this.
