### ISSUE TITLE
Should Clearance's default views display form errors?

### ISSUE THREAD

**Issue by DavidVII** [thoughtbot/clearance#559]
Hello, possibly just a question here. It's my first time using this the clearance gem. I notice `Clearance::User` has uniqueness validation.

However, I notice that if you attempt to sign up with an existing email that there is no error message letting the user know that the email has already been taken. It doesn't look like clearance's default views implements this this. Should it?

**Comment by DavidVII** [comment]
I should note that I'm using the default clearance views. I haven't generated them. Taking a look around the views, it does **not** appear that it's handling form errors. https://github.com/thoughtbot/clearance/blob/master/app/views/users/new.html.erb

**Comment by derekprior** [comment]
Closing for #554 which is a similar discussion
