### ISSUE TITLE
application#url_after_denied_access_when_signed_out incorrect in either README or code

### ISSUE THREAD

**Issue by samjbmason** [thoughtbot/clearance#561]
In the readme this line under the Redirects heading it says this method `application#url_after_denied_access_when_signed_out` uses the `Clearance.configuration.redirect_url` value but it is currently set to `sign_in_url`. Im not sure which one is right?

**Comment by steverob** [comment]
:+1: And just taking this little off topic...

Im new to this project and was going through the code. I found this part interesting - the `application#url_after_denied_access_when_signed_in` & `application#url_after_denied_access_when_signed_out`.

This is being used here - 
```ruby
module Clearance
  module Authorization
    ...
    ...
   protected

     def redirect_request(flash_message)
       ...
       if signed_in?
         redirect_to url_after_denied_access_when_signed_in
       else
         redirect_to url_after_denied_access_when_signed_out
       end
     end
  end
end
```

And `redirect_request` is called from `deny_access` which in called by `require_login` in the first place - 
```ruby
def require_login
  unless signed_in?
    deny_access
  end 
end
```

So I was wondering, if the `redirect_request` is called only if `!signed_in?` is `true` why is this condition being checked again inside `redirect_request`?

Just asking this for educational purposes :) @derekprior Thanks!!

Btw enjoying reading through this lovely code.

**Comment by derekprior** [comment]
> So I was wondering, if the redirect_request is called only if !signed_in? is true why is this condition being checked again inside redirect_request?

It's possible this was used in multiple places before, and even if it never was it's a potentially useful method when integrating with authorization frameworks. You can call `redirect_request` and have it act as clearance would using the same settings.

**Comment by derekprior** [comment]
@samjbmason - this has been corrected. Thanks for bringing it to our attention.
