### ISSUE TITLE
Create flash message for require_login?

### ISSUE THREAD

**Issue by samjbmason** [thoughtbot/clearance#562]
When a user tries to access a page which requires authentication, it would be great to have a flash message after it redirects them to the `sign_in_url` where we could say that a user needs to be logged in to perform that action.

**Comment by derekprior** [comment]
Is being redirected the login form not a sufficient enough notification that the users needs to log in?

**Comment by rodrigodealer** [comment]
I think it's a good idea. I'll make a PR and then you guys can evaluate it.

**Comment by derekprior** [comment]
Closed with #597
