### ISSUE TITLE
user_id_parameter doesn't work well with a namespaced user model

### ISSUE THREAD

**Issue by zavan** [thoughtbot/clearance#587]
Supose my user model is namespaced:

``` ruby
module Auth
  class User < ActiveRecord::Base
    include Clearance::User
  end
end
```

There is no need to change the table name or anything, because it's a module namespace, not a class.

I then configure Clearance to use it:

``` ruby
Clearance.configure do |config|
  config.user_model = Auth::User
end
```

With the default routes, password updates stop working, because Clearance expects `user_id_parameter` to return `auth_user_id`, as defined in [this configuration method](https://github.com/thoughtbot/clearance/blob/b9700d100cfc5af1c0b3f027415b622f38c870eb/lib/clearance/configuration.rb#L124-L130).

**Comment by derekprior** [comment]
Can you come up with a way to get the foreign key name programmaticly that would work with this case? Using `table_name.singularize` might work in this case better than `model_name.singular` but I'm just not sure it's more reliable overall.

**Comment by zavan** [comment]
I think this is more of a routing related problem, than a model or table related one. It seems that the model or table name means nothing to the route param name, what defines it is the resource name in the route, so:

``` ruby
resources :users, controller: 'clearance/users', only: [:create] do
  resource :password, controller: 'clearance/passwords', only: [:create, :edit, :update]
end
```

Generates:

```
POST   /users/:user_id/password(.:format)
GET    /users/:user_id/password/edit(.:format)
PATCH  /users/:user_id/password(.:format)
PUT    /users/:user_id/password(.:format)
POST   /users(.:format)
```  

But if you change from `:users` to `:admin_users`, but change nothing in the model or table name:

``` ruby
resources :admin_users, controller: 'clearance/users', only: [:create] do
  resource :password, controller: 'clearance/passwords', only: [:create, :edit, :update]
end
```

It generates:

```
POST   /admin_users/:admin_user_id/password(.:format)
GET    /admin_users/:admin_user_id/password/edit(.:format)
PATCH  /admin_users/:admin_user_id/password(.:format)
PUT    /admin_users/:admin_user_id/password(.:format)
POST   /admin_users(.:format)
```

But I don't think we can easily programatically get this route resource name...
I think our best option is to default to `model_name.singular` but let the user configure it:

```ruby
Clearance.configure do |config|
  config.user_id_parameter = :admin_user_id
end
```

**Comment by derekprior** [comment]
I haven't worked in a context where the thing I'm authorizing is namespaced. I'm not against a fix for this so long as we can find one that works for the existing cases and also addresses this, but I can't say I'm going to spend much of my own time on it. I'm going to close this for now, but if you'd like to work on it and ask questions via this issue then I'll re-open.

That offer goes for anyone else that might stumble on this issue.
