### ISSUE TITLE
Email validation on sign up

### ISSUE THREAD

**Issue by GCorbel** [thoughtbot/clearance#589]
Hello,

I see there is no email validation on sign up. Is there a standard way to do I have to do it myself? It can be useful to have an option.

What you think?

**Comment by derekprior** [comment]
There is not currently a built-in option for doing email confirmation. There used to be an option for this a number of years ago, but we've found it to be a cargo-culted practice that doesn't actually give most sites anything of value compared to the hassle it causes users. It's one of the opinions Clearance holds.

That said, I *have* worked on sites where this was a necessity, so we've been improving the story on how to handle this type of functionality yourself. I've also been writing a lot of documentation lately, which may help.

1. You will need to add two columns to your user model or to a join model: `email_confirmation_token` and `email_confirmed_at` (or a boolean if you'd rather).
2. On registration of a new user, be sure to generate an email_confirmation token and also deliver an email with the confirmation link.
3. Write the email confirmation controller that marks the user as confirmed and blanks the token.
4. Write and configure a [Sign In Guard] that disallows sign in by users that are not confirmed.
5. For extra credit: handle this process again when the user changes their email addrress.

[Sign In Guard]: https://github.com/thoughtbot/clearance/blob/master/lib/clearance/sign_in_guard.rb

We attempt to provide the controller extension points that might make sending that email possible and the Sign In Guards that allow you to block sign in for any number of reasons.

I do think that a well done email confirmation process might make for an interesting gem available as an extension to clearance.

**Comment by GCorbel** [comment]
Thanks @derekprior for your help. I think it may cause a security issue because we have to check if email addresses are real. I will check if I create a gem.

**Comment by derekprior** [comment]
we do validate emails for proper format, using the email_validator gem. We just don't validate that it's deliverable or that the user owns them.

You could potentially monitor bounces for marking a user as having an invalid email. Another approach I took on a project once was to have every single email we ever sent a user contain a confirmation parameter in the links. If the user ever once clicked a link from an email we'd confirm that address using an application controller before_filter. So it was more of a passive email confirmation.

**Comment by GCorbel** [comment]
Thanks for suggestions. I think the simplest is to have a confirmation email. It's pretty common and, I think, users are accustomed.

**Comment by derekprior** [comment]
Here are some old numbers from a product we ran with email confirmation:

> We have numbers that show you lose customers this way. In one example, we have a consumer app with 9,204 email sign ups, but only 4,607 confirmations.

Source: https://robots.thoughtbot.com/email-and-password-confirmation-bias

That source is old and the result anecdotal rather than scientific, but it mirrors my experience. I'm not trying to disuade you in particular from adding this feature to your specific app -- mostly just trying to document the entire conversation since this request comes up somewhat frequently.
