### ISSUE TITLE
How can I change email validation rules on Clearance::User

### ISSUE THREAD

**Issue by benlivermore** [thoughtbot/clearance#590]
Our product uses Clearance and needs to allow apostrophes in the local part of the email for a particular client who apparently has email addresses with apostrophes.  `Clearance::User` currently invalidates these emails.   So far we've only come across ugly hacks to solve this issue. 

Is there an accepted way to override the email validation?

**Comment by benlivermore** [comment]
After more study, we realized that we could override the email_optional? method have it return true and effectively eliminate the validation so we could add our own.  So we added the following code in the clearance initializer file right after our configure block. 

        module Clearance::User::Validations
          #remove email validation so we can use our own
          def email_optional?
            true
          end
        end

**Comment by derekprior** [comment]
That was going to be my suggestion but you should be able to do it by
defining that method in your user class rather than monkey patching
clearance.
