### ISSUE TITLE
Recent commit in rails breaks compatibility with clearance

### ISSUE THREAD

**Issue by zernie** [thoughtbot/clearance#591]
Starting with [this commit](https://github.com/rails/rails/commit/a1ced8b52ce60d0634e65aa36cb89f015f9f543d), **rails** will throw a runtime error as **clearance** will try to load itself after the _ActionDispatch::ParamsParser_ middleware, which is no longer initialized. 
Although **Rails 5** is not going to be released any time soon, the point remains.

**Comment by derekprior** [comment]
Thanks for the heads up. We won't beging testing with Rails 5 until at least a beta is released. I don't want to make any changes for it just yet, as we may end up shipping Clearance 2 and requiring that for Rails 5 anyway.
