### ISSUE TITLE
Clearance::PasswordsController#url_after_create never called?

### ISSUE THREAD

**Issue by manuelmeurer** [thoughtbot/clearance#600]
It seems like the [`Clearance::PasswordsController#url_after_create`](https://github.com/thoughtbot/clearance/blob/v1.11.0/app/controllers/clearance/passwords_controller.rb#L97) method is never called?

**Comment by derekprior** [comment]
Yeah, I noticed this when I did a documentation pass. The last call to it was removed in `5e107f6695461baa006cb03ed548255ecddd5a7c`. 

I could probably remove it without a problem, but it's another one of those things where this is public API and I can't be sure that someone isn't using it in one of their controller overrides. I think this will have to wait for 2.0 to remove.

What do you think?

**Comment by manuelmeurer** [comment]
But if someone overrides the method in their own controller inheriting from ` Clearance::PasswordsController`, they would have to call it themselves from that controller, since it's not called from ` Clearance::PasswordsController` anymore, right? In that case, removing the method in ` Clearance::PasswordsController` should not break it. Am I thinking correctly? 
But maybe let's wait for v2.0 anyways, better safe than sorry! :smile:

**Comment by derekprior** [comment]
This was fixed in 23f129a7126190a6e715eb885db854977b5038e4, which is in the 2.0 branch.
