### ISSUE TITLE
Flash :alert?

### ISSUE THREAD

**Issue by steverob** [thoughtbot/clearance#602]
Just wondering why you guys are using `:notice` type flashes everywhere - even if it's a failure situation like here - `https://github.com/thoughtbot/clearance/blob/master/app/controllers/clearance/passwords_controller.rb#L86`?

In the app I'm working on, we're looking to give different colors for different types of flashes - green for success, etc.. So Clearance giving same key for all flashes looks weird :)

Would love to know why this is so and if there's a nice way to change this.

**Comment by derekprior** [comment]
I agree. Clearance has been around a long while so conventions and tastes have changed. Changing this is a backwards incompatible change so I'll have to think about the right way to approach it.

Easiest is that we wait for 2.0 and make a breaking change, but we could also allow a configuration for anyone that wants to fix it right now and then remove the configuration in 2.0. Hmmm.

**Comment by derekprior** [comment]
This was addressed by https://github.com/thoughtbot/clearance/pull/672, which was just merged to our new 2.0 branch.

**Comment by jankeesvw** [comment]
I just had the same issue, had a green "Bad email or password." notice in my project. 😊
