### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jrguenther** [thoughtbot/clearance#611]
A few episodes ago on the Bike Shed, Derek, you were talking about wanting to improve the documentation of clearance for beginners. We've just started to use clearance as our goto authentication gem for new projects, so I wonder if I could help. Is there anything you'd like a beginner's (new to clearance, not programming) perspective on?

Also, would you be interested in compiling a list of things devs commonly want to do with clearance? I'm willing to help write some of this content.

For example:
* I'm using Rails 4, how do I use strong parameters with clearance?
* If I want my user to have more fields than a username and password, how do I do that? Do I need to override a controller? Can I use my own controller?
* I want to create a profile page for a user, do I need to override a controller? Use my own? What are my options?

**Comment by derekprior** [comment]
Hello @jrguenther. Sorry it has taken me a long while to get back to you. I have been taking a break from Clearance work, mostly.

As I said on the podcast, this type of documentation appeals to me quite a bit, but it's not immediately clear to me where it should live. I think I made my feelings on wikis for documentaiton pretty well known in that episode and this project's wiki is an example of that.

Right now I'm thinking maybe the best would be a collection of markdown documents in the projects `doc` directory. This would be similar to how rails guides are maintained -- I even like the idea of guides.

To add to what your list, here's what I see for guides:

* Popular Customizations
  * Using Strong Params
  * Adding fields to user registration
  * Requiring password confirmation
  * Requiring email confirmation
  * Suspending users
  * Sign up by invitation only
* Security Guide
  * Securing cookies
  * How overall site security can impact clearance security
  * How database security can impact clearance security

Ideally these guides, particularly the one about customization, would make use of good APIs to enable these customizations (and we would create them where they don't exist) and link to the appropriate API documentation for more information.

What do you think?

**Comment by jrguenther** [comment]
I think what you've described sounds like a great starting place. If other topics come up, we can keep a list in this thread and tackle them as we have time.

I think using `doc`s as a place to store the copy is a great idea. It keeps the docs in the repo and at the ready. If we want to get fancy down the road, we can eventually transition the docs folder into github pages, or maybe both. Using markdown will make that easy.

**Comment by derekprior** [comment]
We can also include the guides as documents that are available with the documentation generated by yardoc.

**Comment by jrguenther** [comment]
Definitely. I forgot about those.

**Comment by jrguenther** [comment]
How do I user a model other than `User` as my user model?

**Comment by derekprior** [comment]
Not actionable right now. Closing.
