### ISSUE TITLE
Clearance::PasswordsController.find_user_for_edit cannot find url with non-id parameter

### ISSUE THREAD

**Issue by coneybeare** [thoughtbot/clearance#615]
I use `friendly_id` on my `User` model which sets the `to_param` field to a username amongst other things.

When resetting a password using Clearance, the proper URL is generated using said friendly id:
````
http://my.domain.com/admin/users/foobar/password/edit?token=331fa371c41ebf588c3e2f32f7441eeb658a2993
````

However, when clicking this link, the `Clearance::PasswordsController` [expects](https://github.com/thoughtbot/clearance/blob/7a63a2a9363729c743693d74f725337b860ee314/app/controllers/clearance/passwords_controller.rb#L62) a numeric id for `find_user_for_edit` in the `find_user_by_id_and_confirmation_token` method.

I can fix my error by overriding the `User.find_user_by_id_and_confirmation_token` method to actually do a find with the username, but I shouldn't have to. If the link generated includes the friendly id, then the finders within Clearance should not be hardcoded for the numeric record id.

**Comment by coneybeare** [comment]
If thoughtbot decides not to address this, I fixed it by subclassing the `PasswordsController` and overriding the `find_user_by_id_and_confirmation_token` method to look like this:

````
  private
  
  def find_user_by_id_and_confirmation_token
    user_param = Clearance.configuration.user_id_parameter
    Clearance.configuration.user_model.where(confirmation_token: params[:token].to_s).friendly.find(params[user_param])
  end
````

**Comment by derekprior** [comment]
It doesn't expect a numeric `id` so much as it expect to be able to use the `id` field for a query. I think what you have done is the correct solution for now. You also could have implemented `find_by_id_and_confirmation_token` on your `User` model to do what you need, but I think I like what you did better.

**Comment by ariefrizkyr** [comment]
Hi @coneybeare , thank you for your suggestion. I tweaked a little bit the code since I can't make it work. Here is my workaround. I made the token to a variable and it can be it's token or password_reset_token

`def find_user_by_id_and_confirmation_token
        user_param = Clearance.configuration.user_id_parameter
        token = params[:token] || session[:password_reset_token]
        Clearance.configuration.user_model.where(confirmation_token: token.to_s).friendly.find(params[user_param])
    end`

Thank you once again!
