### ISSUE TITLE
Duplicate cookie sent when using cookie domains

### ISSUE THREAD

**Issue by coryodaniel** [thoughtbot/clearance#616]
When using cookie domains two cookies were being sent to the browser:
1. a domain cookie
2. a regular cookie

Also, logging out would only the regular cookie to get deleted because the [sign out method](https://github.com/coryodaniel/clearance/blob/master/lib/clearance/session.rb#L80) ignored if the domain was set. This would cause one cookie to still be set in the browser after log out, and create bizarre bouncy redirects when you logged in again (because the remember token was set the the previous session's remember token).

Here is my config:

``` ruby
Clearance.configure do |config|
  config.cookie_name = "remember_token_#{Rails.env}"
  config.mailer_sender = %("Oh hi" <hello@example.com>)
  config.password_strategy = Clearance::PasswordStrategies::BCryptMigrationFromSHA1
  config.cookie_domain = ".example.com"
  config.cookie_expiration = ->(cookies) { cookies['remember_me'] ? 1.year.from_now.utc : nil }
  config.secure_cookie = true
  config.httponly = true
end

```

Note: this is specifically for version 1.8.x, I wasn't able to upgrade to 1.12 due to a gem conflict, but the sections of changed code are the same.

I created a [branch](https://github.com/coryodaniel/clearance/tree/wonky_cookie_domain) with the fixes. It broke some expectations and I didnt put coverage in (because I'm a huge jerk). I wanted to get this ticket opened as a reminder while I send this up to my staging environment to see if its working across all my multi tenant domains.

I'll do a proper set of coverage and a PR against master once I have confirmed. Which branch should I make a PR against for the 1.8.x versions? Are you guys working on a 1.8.2?

<img width="881" alt="results from session create -clearing cookies and then logging into" src="https://cloud.githubusercontent.com/assets/11587/11706164/0d51a566-9eab-11e5-8993-1ed91c78a402.png">

**Comment by coryodaniel** [comment]
For the failing tests, a lot of the tests are written around a method #add_cookie_to_headers which is called in the middleware Clearance::RackSession. 

This isn't actually required as rails writes the Set-Cookie header for anything in the cookies collection and is what causes the double remember token cookie being sent in the event a domain cookie is used:

[This](https://github.com/thoughtbot/clearance/blob/master/lib/clearance/session.rb#L57) will cause rails to write the cookie and [this](https://github.com/thoughtbot/clearance/blob/master/lib/clearance/rack_session.rb#L24) writes an additional cookie. When you arent using domain cookies *no problem*, when you are using them the [first](https://github.com/thoughtbot/clearance/blob/master/lib/clearance/session.rb#L57) time the cookie is set, its set without the domain portion being present and that is were the second (standard) cookie comes from.

If you apply the PR everything works fine, but a ton of tests fail because they are written just working at the rack layer and using the #add_cookie_to_headers method to set the cookies.

I'm going to remove all those tests, and put equivalent tests in the [sessions controller spec](https://github.com/thoughtbot/clearance/blob/master/spec/controllers/sessions_controller_spec.rb) to simulate rails setting them.

LMK if this is crazy talk and Im missing something.

**Comment by coryodaniel** [comment]
I have added the specs to my [branch](https://github.com/coryodaniel/clearance/tree/wonky_cookie_domain) to cover this issue.

Also created PR #617 against master. I didnt see a branch for 1.8x

**Comment by nzgrover** [comment]
@coryodaniel We have encountered this issue as well and found that your branch fixed the issue. I'd like to create "a failing test case, with no code changes, that describes the problem" as requested by @derekprior on your pull request, but are unsure on how to do so. Would this need to be a feature spec to hit both the rack and rails code that creates the cookies? Have you looked into this?

**Comment by coryodaniel** [comment]
Feature or a request spec test should trigger it. We have actually started to move off of clearance so I never got around to the test case. Sorry! :(

**Comment by MSchmidt** [comment]
I've created a minimal example application to showcase the issue: https://github.com/MSchmidt/clearance-cookie-example

Hope this helps.

**Comment by dholdren** [comment]
for anyone still following this issue, I put up a PR here: https://github.com/thoughtbot/clearance/pull/767

**Comment by rtymchyk** [comment]
A little insane that this issue is still open. Here is a hack to get it working based on the PRs put up by @coryodaniel and @dholdren:

```ruby
Clearance::Session.class_eval do
   def sign_in(user, &block)
    @current_user = user
    status = run_sign_in_stack

    if status.success?
      # MODIFIED CODE START
      # ORIGINAL: cookies[remember_token_cookie] = user && user.remember_token
      cookies[remember_token_cookie] = cookie_value.merge(value: user && user.remember_token)
      # MODIFIED CODE END
    else
      @current_user = nil
    end

    if block_given?
      block.call(status)
    end
  end

  def sign_out
    if signed_in?
      current_user.reset_remember_token!
    end

    @current_user = nil
    # MODIFIED CODE START
    # ORIGINAL: cookies.delete remember_token_cookie
    if Clearance.configuration.cookie_domain.present?
      cookies.delete remember_token_cookie, domain: Clearance.configuration.cookie_domain
    else
      cookies.delete remember_token_cookie
    end
    # MODIFIED CODE END
  end
end
```

**Comment by mjankowski** [comment]
Closing this on the assumption that https://github.com/thoughtbot/clearance/pull/804 correctly handled the dupe setting issue. I'm going to leave https://github.com/thoughtbot/clearance/pull/808 open until I can verify that deletion is handled correctly in latest release.
