### ISSUE TITLE
Rails 5 raises errors on skip_before_filter if the callback hasn't been made

### ISSUE THREAD

**Issue by j-dexx** [thoughtbot/clearance#621]
[Method link] (https://github.com/rails/rails/blob/master/activesupport/lib/active_support/callbacks.rb#L632) for rails where it occurs

This means if `before_action :require_login` hasn't been set in the application controller clearance's sessions, passwords and users controller will raise errors.

Can be remedied by either updating the documentation to say that you need to add them in, or by adding them to the authorization module.

    module Clearance
      module Authorization
        extend ActiveSupport::Concern

        included do
          # hide_action :authorize, :deny_access, :require_login
          before_action :authorize, :require_login      
        end
      end
    end

Hide action commented out as support for this was dropped in rails 5.

**Comment by derekprior** [comment]
It seems like we should be able to pass `raise: false` as an option to `skip_before_filter`.

**Comment by j-dexx** [comment]
@derekprior Yes, that works nicely and is also fine with rails 4.

**Comment by derekprior** [comment]
Closed by 23d93b8
