### ISSUE TITLE
If you configure user model, you cannot save the record on signup.

### ISSUE THREAD

**Issue by jrguenther** [thoughtbot/clearance#635]
https://github.com/thoughtbot/clearance/blob/master/app/controllers/clearance/users_controller.rb#L52

If you configure the user model in an initializer, records don't save. This is because the user params method is looking for `:user` instead of a symbol based on the configured user model. In my case `Person`.

**Comment by jrguenther** [comment]
Using `Clearance.configuration.user_model.name.parameterize.to_sym` as the key will solve the problem.

**Comment by derekprior** [comment]
@jrguenther Do you want to work up a patch?

**Comment by jrguenther** [comment]
Yes, I will.

**Comment by jrguenther** [comment]
Ok, I'm part of the way into the patch. How do I create a new migration and apply it for the test runner? `rake db:migrate` is not working.

I need to be able to create a `Person` object instead of a user. I've added the `Person` model to dummy/app/models. When I run the tests, it's tell me that I am missing a table.

**Comment by derekprior** [comment]
Closed by #643
