### ISSUE TITLE
Make user enumeration by timing attacks more difficult

### ISSUE THREAD

**Issue by derekprior** [thoughtbot/clearance#636]
When authenticating a user, we skip any calls to BCrypt if we weren't able to find a user with the provided email address. This results in a faster response time to the client and less work on the server... but it also means one could possibly monitor the response times from the app to see if the provided user has an account.

When we detect that a user does not exist with the provided email, we should go ahead and perform a bcrypt check anyway, and always return false from that check. This will keep timings consistent with the response one gets when they use an email that exists but get the password wrong.

I took a quick look at how this could be done. I feel like the best way would be a new "dummy_authenticate" method on the password strategy that is called for this explict purpose. That's a breaking change to the contract of the password strategy though.

Another alternative would be to handle this in the user mixin itself. We'd want to make sure we produce similar timings in any event.

**Comment by mike-burns** [comment]
As I understand it, the strategy's `#authenticated?` method (e.g. https://github.com/thoughtbot/clearance/blob/7a63a2a9363729c743693d74f725337b860ee314/lib/clearance/password_strategies/bcrypt.rb#L12 ) needs to take a constant amount of time. So changing all the `#authenticated?` methods in `lib/clearance/password_strategies` should do it?

```ruby
def authenticated?(password)
  result = ::BCrypt::Password.new(encrypted_password || "") == password
  encrypted_password.present? && result
end
```

**Comment by magikid** [comment]
[User#authenticate](https://github.com/thoughtbot/clearance/blob/master/lib/clearance/user.rb#L117) would also need to be updated in order to make it to the `#authenticated?` method.

**Comment by mike-burns** [comment]
Great catch, and now I see why @derekprior thought it should be an API change.

I just tried sketching out an API that is resistant to timing attacks but I couldn't do it quickly.

**Comment by halogenandtoast** [comment]
@mike-burns you also can't do `BCrypt::Password.new(encrypted_password || "")` because `""` is not a valid hash and it will throw `BCrypt::Errors::InvalidHash`. You could do a cheap hashing implementation BCrypt::Password.create("", cost: 1), but I don't know if a cost of 1 will create a recognizable difference for a timing attack (basically it would now take slightly longer for accounts that don't exist).

**Comment by sgrif** [comment]
You could always just use some random valid bcrypt hash instead of `""` there.

**Comment by janjiss** [comment]
There is an option of just doing the dry run of encryption if the condition fails. Meaning that in terms of time comparison of encrypted string with `Password.new("encrypted_string") == "password"` is roughly the same as doing `Password.create("random_stuff")`

Here are some benchmarks to prove it:
```ruby
n = 1000

Benchmark.bm do |x|
  x.report { n.times { BCrypt::Password.create("Hello") } }
  x.report { n.times { BCrypt::Password.new("$2a$10$fELdjGQGJU23naA9lon9FO8jPlrFiDwFcyU2BcnEtg9NfTzfEhmVW") == "Hello" } }
end
```
Result:
```
       user     system      total        real
  65.270000   0.150000  65.420000 ( 65.590176)
  65.800000   0.130000  65.930000 ( 66.031897)
```

So what I am getting at here is that it might be good to have authenticated method that looks like this:

```ruby
def authenticated?(password)
  if encrypted_password.present?
    ::BCrypt::Password.new(encrypted_password) == password
  else
    ::BCrypt::Password.create("my_random_string")
    false
  end
end
```

Please note that I am not a security expert and my assumptions might not be correct. :)

**Comment by huntr-helper** [comment]
👋 Hey! We've recently opened a bug bounty against this issue, so if you want to get rewarded 💰 for fixing this vulnerability 🕷, head over to https://huntr.dev!
