### ISSUE TITLE
Using the EmailConfirmationGuard 

### ISSUE THREAD

**Issue by dakotalightning** [thoughtbot/clearance#637]
https://github.com/thoughtbot/clearance#extending-sign-in

I have a question about the `EmailConfirmationGuard` as a `SignInGuard`. Because of the stack of the SignInGuard's, it will always fail for logins that don't exist, wrong passwords, etc. 
*I'm currently experiencing this now*

What is the recommended way to alleviate that without rewriting the usual SignInGuard checks that don't get fired?

**Comment by gylaz** [comment]
I ran into a similar issue. To solve it, I had to check if the user was **not** signed in and let another guard (in this case Clearance's `DefaultSignInGuard`) handle the failure.

Something like this:
```rb
class ActiveUserGuard < Clearance::SignInGuard
  def call
    if !signed_in?
      next_guard
    elseif current_user.active?
      next_guard
    else
      fail("Some message.")
    end
  end
end
```

**Comment by dakotalightning** [comment]
Thanks :)
