### ISSUE TITLE
Disable flash messages

### ISSUE THREAD

**Issue by naps62** [thoughtbot/clearance#638]
I want to disable this particular flash message: https://github.com/thoughtbot/clearance/blob/7e7936d4e689fb45db22e56bb39a7b7ca475f294/lib/clearance/authorization.rb#L22

Am I supposed to override `require_login` in my app if I want to do so? Or should there be a way for me to configure this within clearance?

**Comment by magikid** [comment]
When you say you want to disable the flash message, do you mean that you want to replace it with your own message or remove the flash altogether?

If you want to replace the message, you can set your own in the I18n file in your application.

If you'd like to remove the flash completely, I'd suggest writing your `before_action` method that checks the user is signed in.

**Comment by derekprior** [comment]
You could also set the i18n explicitly to an empty string and make sure your flash-rendering code checks `present?` before displaying the value.

**Comment by derekprior** [comment]
I think the two solutions above should do the trick. If they aren't sufficient, let me know.
