### ISSUE TITLE
Rails 5 - Turbolinks

### ISSUE THREAD

**Issue by petermumford** [thoughtbot/clearance#649]
Using the **require_login** filter fails when using a simple **link_to** method as Rails thinks it's a **JS** request, which is true when using Turbolinks but I want it to redirect as I am not expecting it to return **JS**. If I add `data-turbolinks="false"` to the **link_to** method it works as expected by redirecting me. The error I get in console is below:

_Error:_
> GET http://localhost:3000/organisers/1/events/1/edit 401 (Unauthorized)Turbolinks.HttpRequest.e.send @ turbolinks.self-6e94c8831ec7361b6d91dc05b335643dba203d4358fa902bf427adfd3c51916b.js?body=1:6Turbolinks.Visit.e.issueRequest @ turbolinks.self-6e94c8831ec7361b6d91dc05b335643dba203d4358fa902bf427adfd3c51916b.js?body=1:6Turbolinks.BrowserAdapter.e.visitStarted @ turbolinks.self-6e94c8831ec7361b6d91dc05b335643dba203d4358fa902bf427adfd3c51916b.js?body=1:6Turbolinks.Visit.e.start @ turbolinks.self-6e94c8831ec7361b6d91dc05b335643dba203d4358fa902bf427adfd3c51916b.js?body=1:6Turbolinks.Controller.e.startVisit @ turbolinks.self-6e94c8831ec7361b6d91dc05b335643dba203d4358fa902bf427adfd3c51916b.js?body=1:6Turbolinks.Controller.e.startVisitToLocationWithAction @ turbolinks.self-6e94c8831ec7361b6d91dc05b335643dba203d4358fa902bf427adfd3c51916b.js?body=1:6Turbolinks.BrowserAdapter.e.visitProposedToLocationWithAction @ turbolinks.self-6e94c8831ec7361b6d91dc05b335643dba203d4358fa902bf427adfd3c51916b.js?body=1:6Turbolinks.Controller.e.visit @ turbolinks.self-6e94c8831ec7361b6d91dc05b335643dba203d4358fa902bf427adfd3c51916b.js?body=1:6Turbolinks.Controller.e.clickBubbled @ turbolinks.self-6e94c8831ec7361b6d91dc05b335643dba203d4358fa902bf427adfd3c51916b.js?body=1:6(anonymous function) @ turbolinks.self-6e94c8831ec7361b6d91dc05b335643dba203d4358fa902bf427adfd3c51916b.js?body=1:6

_My code:_
`before_action :require_login, except: [:show]`
`<%= link_to 'Edit', edit_organiser_event_path(@organiser, @event) %>`

The issue is coming from [here](https://github.com/thoughtbot/clearance/blob/master/lib/clearance/authorization.rb#L54). Am I not understanding how the filter works or is this a bug when using **require_login** with Turbolinks 5.

_Versions:_
- Ruby: 2.2.3
- Rails: 5.0.0.beta3
- Clearence: master branch

**Comment by derekprior** [comment]
Clearance returns the `unauthorized` response code to requests that have a `js` format. Redirecting doesn't make sense here because we're not dealing with a browser client.

I'm not experienced with TurboLinks. What do you think should happen here?

**Comment by derekprior** [comment]
To be clear, `require_login` isn't failing. It's behaving as it should, as far as I can tell. What does turbolinks expect to be returned in cases where there should be a redirect?

**Comment by petermumford** [comment]
Hi @derekprior, I was meant to say I've reported a bug on Rails and they seem to be aware of it already: rails/rails#24035

I hope this helps you?

**Comment by derekprior** [comment]
Ah yes, I think I see now. Thanks for that. I'll keep an eye on that issue but I think we're good in clearance for now.

**Comment by petermumford** [comment]
Yes I am and thank you.
