### ISSUE TITLE
Bypass authentication with secure token

### ISSUE THREAD

**Issue by steverob** [thoughtbot/clearance#651]
I am wondering how I should implement this strategy. I want to allow people with a URL with a secure token to access a page which is behind clearance authentication. I dont want them to log in as a user. Need a way to provide a dummy `current_user` object as well. Any tips?

**Comment by derekprior** [comment]
I'd consider using a before_action other than require_login. Something like `require_login_or_secret_token`:

```ruby
def require_login_or_secret_token
  unless params["super_secret_security_token"] == TOKEN
    require_login
  else
end
```

Then you'd need to override current_user to return a guest object rather than nil:

```ruby
def current_user
  super || Guest.new
end
```

Or something like that. This advice isn't perfect, but that should be enough to get you started.

**Comment by steverob** [comment]
Thanks a a lot @derekprior. Was able to solve this with your tips :+1: :heart: the BikeShed btw! Thanks!
