### ISSUE TITLE
initializer loads User too early for paperclip

### ISSUE THREAD

**Issue by jrochkind** [thoughtbot/clearance#655]
I have a `config/initializers/clearance.rb`, as recommended, with:

     config.user_model = User

At the point this gets loaded by Rails, the User model is then auto-loaded. 

But I am also wanting to use Paperclip in my user model.  Somehow, at the point the User auto-loading is triggered, paperclip's `has_attached_file` is not yet available. I get a `method_missing: undefined method `has_attached_file' for User`. 

Adding a `require 'paperclip'` doesn't help.  I have confirmed that _removing_ the line that references `User` from the clearance initializer gives me `has_attached_file` again at the point User ends up being loaded. 

I'm not sure what's going on. Does paperclip add `has_attached_file` to ActiveRecord::Base in an after_initialize or something, such that anything in an ordinary initializer that loads the User model will always be too early for `has_attached_file` to be available? Which of course is a problem. 

Since paperclip is also from you guys, I'm hoping you have some thoughts? Has anyone else run into this?

**Comment by derekprior** [comment]
`config.user_model = User` is the default. You don't need this line here. If you remove this, does it work?

Are you running the most recent version of clearance?

**Comment by jrochkind** [comment]
clearance 1.12.1, paperclip 4.2.4. 

I see there's a slightly newer clearance, I'll try upgrading... made no difference on clearance 1.13.0. (The slightly old paperclip is required by one of my dependencies). 

I might be able to get away without `config,user_model = User` since it's the default, but it seems bad if you can't use another class name that also includes paperclip, yes?

**Comment by jrochkind** [comment]
A manual:

    extend Paperclip::ClassMethods

In my User class also solves the problem. But this seems a bad workaround, that could have other unforeseen consequences (double-extending of the class methods in some cases?) and may be using not meant to be public Paperclip API.  It doesn't seem a good solution.

**Comment by derekprior** [comment]
I'm confident there's a work around in load order.

I also suspect this might have to do with auto-reloading in development,
but I'm not certain. That's why I asked for the version you are running; an
earlier version of clearance made some improvements when reloading the
configured user model in development.

It hasn't come up in the years maintaining this gem, so I'm not inclined to
spend much time looking into it right now. If you'd like to poke around
more I'd certainly entertain a patch or dig more into if you can provide a
minimal reproduction.

On Thu, Mar 10, 2016 at 3:33 PM, Jonathan Rochkind <notifications@github.com

**Comment by jrochkind** [comment]
Okay, what's the best way to provide a minimal reproduction? Zipped up Rails app?

I will provide the minimal reproduction with a class named something other than User, non-default, to make it clear why it matters.

**Comment by derekprior** [comment]
However you want, but a github repo would probably be easiest.

**Comment by jrochkind** [comment]
Okay, in trying to make a repro, I seem to have solved it by putting `gem 'paperclip'` in my Gemfile _before_ `gem 'clearance'`. 

Oddly, in a very simple minimal reproduction this is _not_ neccesary.  It's got something to do with some of my other dependencies, perhaps `react-rails`, although that doesn't make a lot of sense either, removing `react-rails` from my Gemfile also solved the problem. 

And I can't figure out why Gemfile order would matter -- all the Gem requires should happen before any initialization, and manually adding a `require 'paperclip'` didn't fix things. 

So it doesn't make a lot of sense. But re-ordering my Gemfile to put paperclip at the top seems to solve things, crossing fingers.

**Comment by jrochkind** [comment]
Anyway, okay, I guess that's that. Makes not a lot of sense, but that seems to have solved it. Thanks for your quick response. Guess this closed issue can maybe help someone else who runs into it and tries searching issues.
