### ISSUE TITLE
helper method names quite confusing when using other user_model

### ISSUE THREAD

**Issue by rainerborene** [thoughtbot/clearance#659]
If you have both `User` and `Account` models in your application, it can be quite confusing to understand the scope of the helper methods. I think `user_model` option should define the helper method names suffix. Would you accept a pull request for that?

**Comment by derekprior** [comment]
Which helper methods were you thinking, specifically? `current_user`? I can't say I'm likely to accept making that name dynamic. 

If you want `current_account` then it can be implemented as a helper method:

```ruby
def current_account
  current_user
end

helper_method :current_account
```

I can see how having the extra methods would be annoying but I don't think it's worth moving to `define_method` for.
