### ISSUE TITLE
allow user to change their own password, require current password?

### ISSUE THREAD

**Issue by jrochkind** [thoughtbot/clearance#661]
Clearance has built-in "forgot my password, let me reset it with an email", great. 

I want to actually let the user who is already logged in and has not necceasarily forgotten their password, change their password. 

Naive approach is pretty straightforward, just set the 'password' attribute in the model, no problem. 

But I want to make them re-enter their original password on the request to change their password, for security purposes (maybe they left themselves logged in somewhere, etc), as is often done. 

I'm getting confused about the best way to do this. The `authenticate` controller concern method would let me check their existing password, I think.  But it takes only an email address and password, and the same form that lets them change their password also lets them change their email address in my implementation, which starts to get confusing to make sure I'm using the right email to `authenticate`. 

Is there any supported api for checking if a password verifies against a given User model? Or any other tips?  Thanks!

**Comment by jrochkind** [comment]
I'm actually finding it a bit confusing to even let the user change their password without re-entered old password confirmation!

**Comment by jrochkind** [comment]
Ah, I see, the password validation rules are not applied if I allow direct setting of password on the model. Is this expected?

I am getting the feeling that maybe Clearance does not really support any password setting _except_ through it's own controllers.  Confirm or deny?

**Comment by hani1231** [comment]
email:rame-100@hotmail.com

**Comment by hani1231** [comment]
rame-100@hotmail.com

**Comment by derekprior** [comment]
@jrochkind You can use `User#authenticated?` which is an instance method on the user. See docs: https://github.com/thoughtbot/clearance/blob/master/lib/clearance/user.rb#L68

The method itself is included from the password strategy. It's defined here: https://github.com/thoughtbot/clearance/blob/master/lib/clearance/password_strategies/bcrypt.rb

**Comment by jrochkind** [comment]
thanks!

**Comment by hani1231** [comment]
ga*****

**Comment by hani1231** [comment]
rema-100@hotmail.com

Beg your password

**Comment by verachell** [comment]
I'd love to see such a feature built-in (does not have to look fancy, idea here below). That way, even in a mail function outage or in the most basic tryout conditions, a user can change their own password.

@jrochkind said above:
> I'm actually finding it a bit confusing to even let the user change their password without re-entered old password confirmation!

...  and I'd struggle where to even start, even with the information given in the answer above about User#authenticated? and the bcrypt.rb methods. 

As a beginner/noob with my simple tryout rails app with Administrate and Clearance, I'd love to see something ultra-simple but already functional that developers can extend on their own if needed. 

Suggested functionality:
availability of a pre-built URL such as `/change_password` . Kind-of an analog to `/sign_in` or `/sign_out` that allows currently logged-in users to change their own password (with exactly the same style of simple interface, nothing fancy needed, does not need to be built into dashboard views etc) 

Possible extra: in config/initializers/clearance.rb, offer the option to turn it off, e.g. config.allow_change_password = false

I realize that Clearance ALREADY supports a whole lot of really great features and works really well, so I completely understand if that's not something that warrants extra work in the core. My only concern is that there might be others such as myself who are beginners and want an easy pre-built way to change password from inside a minimal app without requiring email functionality.
