### ISSUE TITLE
Right way to add additional password validations?

### ISSUE THREAD

**Issue by jrochkind** [thoughtbot/clearance#664]
Perhaps I want to require passwords to be 10 characters long (default out of the box clearance will allow 1 character password). 

I try this in my `User` model:

      validates :password, length: { in: 10..128 }, unless: :skip_password_validation?

If I use `user.update_password`, then it indeed validates using that, returns false with validation errors in `user.errors`, great. 

But the [default Clearance new user registration routines](https://github.com/thoughtbot/clearance/blob/master/app/controllers/clearance/users_controller.rb#L49-L54) do not seem to result in `skip_password?` being unset, so my validation is never called on the password entered by a newly registered user, and they can use it no problem.

But if I skip the `unless: :skip_password_validation?`, of course I'll never be able to save a user unless I'm resetting their password, since `password` is not generally exposed. Which is why `skip_password?` is there in the first place for the [one built-in presence validation](https://github.com/thoughtbot/clearance/blob/master/lib/clearance/user.rb#L150), I gather... except even this one built-in validation is probably not called for newly registering users either?

Is there anything I'm missing? Can you give advice on the best way to add additional password requirements in a way that works well with Clearance instead of fighting it? Thanks!

**Comment by derekprior** [comment]
This is a bug. `skip_password_validation?` is defined like so:

```ruby
    # True if {#password_optional?} is true or if the user already has an
    # {#encrypted_password} that is not changing.
    #
    # @return [Boolean]
    def skip_password_validation?
      password_optional? || (encrypted_password.present? && !password_changing)
    end
```

`password_changing` is an attribute on the class that is set by `update_password`, which is why the validations are kicking in then.

My first thought for a fix was to deprecate the attribute and use `encrypted_password_changed?` but I'll need to dig in to see if this makes sense.

**Comment by jrochkind** [comment]
Ah, `encrypted_password_changed?` might make a lot of sense and make things transparent. 

I've been tripped up to this in my own code, not sure the 'right' way to change a password in your own code in Clearance, if there are ways that violate Clearance's contract or not. My own code wasn't tripping the validation, so I dove into Clearance's own code, and learned about `update_password` and  `password_changing`, which made me wonder: "Does Clearance require that you _only_ ever change the password with `update_password`", but then I noticed that Clearance's own controller did not do so -- and indeed did not trip the validation. 

If there's a way to make it transparent Just Work, that would be great -- otherwise it needs some docs on 'right' ways to change a password with Clearance.
