### ISSUE TITLE
Install Generator Broken by Commit 26f460d

### ISSUE THREAD

**Issue by codener** [thoughtbot/clearance#676]
[Commit 26f460d breaks the install generator](https://github.com/thoughtbot/clearance/blob/26f460db13e6657e43a4a60a583e77bd379e7775/lib/generators/clearance/install/install_generator.rb#L27). Broken in v1.14.0.

**Issue:** `include Clearance::User` is injected betweet `class User <` and `ActiveRecord::Base`. The generated code looks like this:

```ruby
class User <   include Clearance::User

ActiveRecord::Base

  # some other code
end
``` 

A fix should be to inject with a regex:

```
          inject_into_file(
            "app/models/user.rb",
            "\n  include Clearance::User\n\n",
            after: /class User < .*$/,
          )
 ```

The install generator spec probably should not only [check for the string](https://github.com/thoughtbot/clearance/blob/26f460db13e6657e43a4a60a583e77bd379e7775/spec/generators/clearance/install/install_generator_spec.rb#L40) to be present, but also check for proper file formatting.

**Comment by abunashir** [comment]
It looks like a bug to me; There was no existing test to check if the generator was including the `Clearance::User` correctly or not.

I've submitted a pull request; It includes the necessary test to check the generator is inserting the content correctly, this should also fix this issue.

Thanks.

**Comment by codener** [comment]
Thanks, great!
