### ISSUE TITLE
Password Confirmation for Password Change

### ISSUE THREAD

**Issue by kcville** [thoughtbot/clearance#679]
I can see that adding a password confirmation for sign up appears to be fairly trivial:

1. Add the validator
2. Add the accessor
3. Create the field in the view

I have a requirement to add a confirmation field to our update password page as well. It looks like I may have to override quite a bit for that. I'm thinking the following three methods:

`PasswordsController#password_reset_params`
`PasswordsController#update_password`
`User#update_password`

I just want see if I am missing a simpler way to do this.

Thanks!

**Comment by kcville** [comment]
I found a way to do it by only overriding

`PasswordsController#find_user_for_create`

After I get the user record I can set the `password_confirmation` field before returning it

**Comment by derekprior** [comment]
Sounds like you sorted this out.
