### ISSUE TITLE
When a user refreshes the page, "if signed_in?" shows the user they are not signed

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/clearance#691]
I'm using "if signed_in?" but it shows logged in users they are not signed in when they refresh the page until they click any action on the site. When they click a link, the header is updated to show that they are signed in.

```
- if signed_in?
   %li.nav-link= link_to current_user.display_name, edit_user_path
   %li.nav-link= link_to "Sign Out", sign_out_path, method: :delete
- else
   %li.nav-link= link_to "Sign Up", sign_up_path
   %li.nav-link= link_to "Sign In", sign_in_path
```

**Comment by derekprior** [comment]
Are you loading any of the page via AJAX? Is turbolinks involved? Are there cache headers involved? Do you see this behavior in development only or also in production?

There's nothing in Clearance itself that could possibly explain this situation where clicking a link shows a user logged in, but refreshing does not. If you can reproduce this in a sample app, I'm happy to take a look.

**Comment by ACPK** [comment]
@derekprior - I apologize for the delay and thanks for taking the time to reply. I've added you to the sample repo, and turbolinks as well as caching is not set up in the test application using clearance.

**Comment by derekprior** [comment]
I'm not able to access the repository, but it's also been quite some time since this issue was opened and I haven't heard of any other issues. It seems like if this were a widespread issue almost every use of Clearance would be broken. I'm going to close for now, but if you have more detail, please add it.
