### ISSUE TITLE
Set cookie for separate domain

### ISSUE THREAD

**Issue by kieraneglin** [thoughtbot/clearance#692]
I need to be able to set a session for an entirely separate domain that still runs off the same server.  I tried passing a block to `sign_in` like so:

    sign_in(user) {
      cookies[:remember_token] = {
        value: user.remember_token,
        expires: 1.year.from_now.utc,
        domain: ".new-domain.com"
      }
    }

and it doesn't work.  Is there a simple way to set cookies on a new domain?

**Comment by derekprior** [comment]
There is a configuration for cookie domain in the README. You should be able to use that. If you are trying to set a cookie for `a.com` from the site `b.com`, I'm not sure that's going to work. I doubt browsers will let you do that, but I'm not sure.
