### ISSUE TITLE
Test helpers don't exist on Rails 5 Minitest integration tests

### ISSUE THREAD

**Issue by zachahn** [thoughtbot/clearance#695]
I hope I'm not missing anything, but the `sign_in` test helper methods don't seem to exist. I think this has to do with the deprecation of controller tests and the preference to use integration tests.

I did some digging, but was unable to find any solution, but the manual sign in method should work for me for now.

Here's a minimum reproduction case:
- https://github.com/zachahn/clearance-minitest-integration
- https://github.com/zachahn/clearance-minitest-integration/blob/master/test/controllers/home_controller_test.rb

```
> rails test
Running via Spring preloader in process 99290
Run options: --seed 50424

# Running:

E

Error:
HomeControllerTest#test_should_be_able_to_log_in_using_`#sign_in_as`:
NoMethodError: undefined method `sign_in_as' for #<HomeControllerTest:0x007fa913d4f0d0>
    test/controllers/home_controller_test.rb:21:in `block in <class:HomeControllerTest>'


bin/rails test test/controllers/home_controller_test.rb:19

E

Error:
HomeControllerTest#test_should_be_able_to_log_in_using_`#sign_in`:
NameError: undefined local variable or method `sign_in' for #<HomeControllerTest:0x007fa9129b2ea0>
    test/controllers/home_controller_test.rb:25:in `block in <class:HomeControllerTest>'


bin/rails test test/controllers/home_controller_test.rb:24

..

Finished in 0.707819s, 5.6512 runs/s, 2.8256 assertions/s.

4 runs, 2 assertions, 0 failures, 2 errors, 0 skips
```

Thanks!

**Comment by ianagne** [comment]
Hi @zachahn.  You are correct that the deprecation of controller tests is the source of these errors.

The generators in Rails 5 create controller tests inherit from `ActionDispatch::IntegrationTest` instead of `ActionController:TestCase`.  In essence, your application no longer has any controller tests.  All "controller" tests generated by your application are integration tests.

This was done because the Rails team was able to considerably speed up integration tests, as explained by DHH [here](https://github.com/rails/rails/issues/22496).  If you want to know how they did it, Eileen Uchitelle gave an [awesome talk](https://windycityrails.com/videos/2015/#10) explaining the process.

If you'd like your controller tests to follow the Rails 5 convention and inherit from `ActionDispatch::IntegrationTest`, you should use [the Clearance::Backdoor middleware](https://github.com/thoughtbot/clearance#user-content-fast-feature-specs) for easy sign-in.

If you'd like your controller tests to inherit from `ActionController::TestCase`, you'll need to manually switch them over.  Then, the controller sign_in helpers should work as expected.  If you choose this option, be aware that controller tests are slated to be extracted from Rails into a gem in Rails 5.1.

**Comment by ro-puente** [comment]
Hi @ianagne. I had the same problem as @zachahn, and I tried to follow your solution using Clearance, but I'm still getting `undefined method 'sign_in'`. I'm new to testing and I'm using Minitest, which doesn't seem like the standard testing framework here.

By any chance did integrated Clearance testing helpers with Minitest? If so, could you share an example please, as I've been googling many many hours by now and couldn't find any documentation with Clearance and Minitest.

**Comment by zachahn** [comment]
In my `test/test_helper.rb` file, I wrote this following code.

```ruby
class ActionDispatch::IntegrationTest
  def manual_sign_in_as(user)
    post session_url, params: {
      session: {
        email: user.email,
        password: user.password
      }
    }
  end
end
```

This lets me do the following in my tests

```ruby
class PostsControllerTest < ActionDispatch::IntegrationTest
  test "user visits index page while logged in"
    user = User.create!(email: "example@example.com", password: "letmein")
    manual_sign_in_as(user)
    get links_url
  end
end
```

However, I just tried setting up what @ianagne suggested and it seems to work.

Rails 5 subclasses controller tests from `ActionDispatch::IntegrationTest` by default, so I only had to follow the instructions on the readme that was linked.

My tests can now read like the following

```ruby
class PostsControllerTest < ActionDispatch::IntegrationTest
  test "user visits index page while logged in"
    user = User.create!(email: "example@example.com", password: "letmein")
    get links_url(as: user)
    # and
    post links_url(as: user), params: { post: { title: "hi" } }
  end
end
```

As @ianagne mentioned, his option should be faster.

**Comment by krsyoung** [comment]
Curious if others have had any other discoveries here.  I'm currently trying to make use of the backdoor code.  The [example](https://github.com/thoughtbot/clearance#fast-feature-specs) references `visit` (which must be rspec), however I'm using Rails 5 with Minitest.

My current problem is that any attempt to do a POST seems to blow up:

```
Error:
RequestsControllerTest#test_should_create_request:
NoMethodError: undefined method `[]' for nil:NilClass
    app/controllers/requests_controller.rb:33:in `create'
    test/controllers/requests_controller_test.rb:43:in `block (2 levels) in <class:RequestsControllerTest>'
    test/controllers/requests_controller_test.rb:42:in `block in <class:RequestsControllerTest>'
```

Which comes from:

```
post requests_url(as: @user, params: { request: { description: @borrow.description, distance: @borrow.distance, price: @borrow.price } })
```

I'm not exactly sure if `as:` is supposed to work here or if I got lucky on the other tests (i.e. everything but `post` seems to work).

Anybody else having luck?

**Comment by derekprior** [comment]
@krsyoung This is a honeybadger issue: https://github.com/honeybadger-io/honeybadger-ruby/issues/215

You can roll back to pre 3.0 until it is fixed.

**Comment by krsyoung** [comment]
Thanks @derekprior! I think had also exceeded my brain quota while I was debugging which wasn't helping the issue :-) 

I'm still mulling through making use of the backdoor (which works) vs the approach @zachahn had used (and the approach suggested by the [Rails guides](http://guides.rubyonrails.org/testing.html#test-helpers)) which has some benefits (and drawbacks) in terms of supporting the geolocation I'm using.
