### ISSUE TITLE
Compatability issue when upgrading to Rails 5

### ISSUE THREAD

**Issue by jarkelen** [thoughtbot/clearance#696]
I am upgrading Rails from `4.2.7` to `5.0.0` and I am using Clearance, which is at `1.14.2`.
When I run `bundle update rails` I get this:
```

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 5.0.0)

    clearance was resolved to 1.14.2, which depends on
      rails (>= 3.1)
```

What should I do? Because I assume the latest clearance version would support Rails 5?

**Comment by derekprior** [comment]
It does support Rails 5 and we do test against it. Was there more to your error message than what you pasted?

**Comment by jarkelen** [comment]
No, when I do a `bundle update`  I get the mentioned bundler version error. This is (part of) the `Gemfile`:

source 'https://rubygems.org'

```
ruby '2.3.1'

gem "rails", "5.0.0"
gem "clearance"

```

**Comment by jarkelen** [comment]
My mistake, it has to do with another gem which needs another version of Rails. It has nothing to do with Clearance. I will close this issue.
