### ISSUE TITLE
Git repo has warnings and errors

### ISSUE THREAD

**Issue by mike-burns** [thoughtbot/clearance#697]
```
~/clearance% git fsck
Checking object directories: 100% (256/256), done.
warning in tree 5e82b08e97aa30596775a703591ced10bb718961: contains zero-padded file modes
warning in tree 92e592eb0e20c6520373bd5523646fff6bb0e5c8: contains zero-padded file modes
warning in tree 0a85626daddd50aa1c927a6b19ec186a0ef268a7: contains zero-padded file modes
warning in tree e03202a656a076c3c7e164b0eb4952d794067868: contains zero-padded file modes
Checking objects: 100% (11316/11316), done.
dangling commit 0e81eca66ea4950be017fbce2aab16635be5a2fe
dangling commit 0ea301d7f407b6d68812867f577955b4d1eaeb9c
dangling commit e9ae04b43010c181f6017a29605027bcad5b7c8f
dangling commit c8b924507d9f3e7d362e42c25f635dc220670234
dangling commit cdcc295a116503fc021d0441269600cd9fe25134
dangling commit 31d1090295a37b56895805e4790b251e980eabf9
dangling commit cb518b5eaa6cd12dcd835e0c968f04343babc2b3
dangling commit 275c906771ea76c41e0a538330eb6f6513602106
dangling commit 806dadca9f31fb5bce343c7c388b56988e292068
dangling commit d6f220f769d29d69da7e02685e4a27eb131b0083
dangling commit ed7c763751d2efc7c63a507ecfd0904efc946967
```

This is with an already-cloned-out repo. With git 2.1.4 I also see this problem:

```
% git clone git@github.com:thoughtbot/clearance.git
Cloning into 'clearance'...
remote: Counting objects: 13889, done.
remote: Compressing objects: 100% (6/6), done.
error: object 5e82b08e97aa30596775a703591ced10bb718961:contains zero-padded file modes
fatal: Error in object
fatal: index-pack failed
```

[StackOverflow recommends](https://stackoverflow.com/questions/14700502/how-to-fix-git-zero-padded-file-modes-warning) a `git-fast-export` pipe `git-fast-import`, with the warning that it will change SHAs.

**Comment by mike-burns** [comment]
cf. https://github.com/jasmine/jasmine/issues/1052

**Comment by derekprior** [comment]
I don't know what "contains zero-padded file modes" means and why its a problem? Or why a dangling commit would be a problem? WIthout knowing this it's hard to judge if rewriting history to solve this is appropriate.

**Comment by mike-burns** [comment]
Forgot to add, which I discovered later, that this is what causes it to fail when I clone a fresh repo:

```
[transfer]
  fsckObjects = true
[fetch]
  fsckObjects = true
[receive]
  fsckObjects = true
```

**Comment by magikid** [comment]
As far as I can tell, the only problem with zero-padded files is that if you have two identical files one with zero-padded file modes and one without, they will have different SHAs.

I don't think this is worth rewriting the whole repo for.

**Comment by derekprior** [comment]
I don't think this is worth re-writing history for. If someone else has another fix or feels strongly that this should be fixed, please let me know.
