### ISSUE TITLE
Intentions for password presence validation

### ISSUE THREAD

**Issue by Mrjaco12** [thoughtbot/clearance#699]
I've recently been working on upgrading clearance from [1.13.0 to 1.14.0](https://github.com/thoughtbot/clearance/compare/v1.13.0...v1.14.0) and I noticed some functionality we were relying is now broken and I wasn't sure if we were relying on unintended behavior or if something was broken.

The basic gist is that on user update, we were submitting an empty string in the password field to signify no update was being requested and this worked fine in 1.13 but now in 1.14 our validations are failing with a password cannot be nil error. I was able to track down the culprit to [this line](https://github.com/thoughtbot/clearance/blob/v1.14.0/lib/clearance/user.rb#L110):

```ruby
def password=(value)
  encrypted_password_will_change!
  super
end
```

Which assumes that the password will always change if password set is called and it will trigger the password validations [here](https://github.com/thoughtbot/clearance/blob/v1.14.0/lib/clearance/user.rb#L169). However, at least with the Bcrypt strategy [this is not the case](https://github.com/thoughtbot/clearance/blob/v1.14.0/lib/clearance/password_strategies/bcrypt.rb#L21):

```ruby
def password=(new_password)
  @password = new_password

   if new_password.present?
    self.encrypted_password = encrypt(new_password)
  end
end
```

So I would like some clarification on the intention here and then we can talk about a fix if appropriate. Thanks!

**Comment by derekprior** [comment]
There's a good deal of explanation about this change in the issue #664 and the corresponding change in #668. Indeed, someone even raised this concern in the PR, but I dismissed it as a bug. Thinking more on it now, I think it's probably a bigger issue than I had perhaps thought. Still, the old way also seemed like a bug. 

The fix on an application's end is to strip out blank passwords from the params being passed to `user.update`. This is more work for you, but thinking objectively it also seems more correct. Previously, you were relying on Clearance ignoring that you were requesting a blank password. Something like: `user.update!(password: "")` could actually succeed while it didn't actually do what it seems I told it to do - set the password to the blank string.

I think the way it operates now is correct but I'm willing to entertain counter points or alternate solutions.

**Comment by Mrjaco12** [comment]
Thanks for the explanation and links @derekprior. I think I agree with you about the approach. So we can close this issue. It might be a good idea to document the intentions a bit somewhere cuz I hunted through a few issues but I must have skipped over the right one to look at.
