### ISSUE TITLE
validate current user password

### ISSUE THREAD

**Issue by wenweih** [thoughtbot/clearance#703]
thx for contributor nice work.  
is there a feature to validate current password?  
my situation is that :  when current user do sensitive operations, for example delete something ,current user must to input their own password, which as second validation.  
many thanks. 🍺

**Comment by derekprior** [comment]
There's nothing for this out of the box, but you can add the password to your form and use `User#authenticate` (see docs) in the controller before proceeding.

**Comment by ACPK** [comment]
@wenweih - What did you end up doing?

**Comment by wenweih** [comment]
@ACPK ```user.authenticated?(password)```  
we can see it in the [lib/clearance/user.rb#L137](https://github.com/thoughtbot/clearance/blob/d72696fc6d32cdee219e64d392141eb1cda1ab3b/lib/clearance/user.rb#L137)
