### ISSUE TITLE
Issue with session and registration controllers

### ISSUE THREAD

**Issue by kinsomicrote** [thoughtbot/clearance#705]
When I point my browser to `http://localhost:3000/sign_up` I get the error:

```
NoMethodError in Clearance::UsersController#new
undefined method `signed_in?' for #<Clearance::UsersController:0x007f44103bd1d8> Did you mean? sign_in_url
```
When I point to: `http://localhost:3000/sign_in`, I get this one:

```
NoMethodError in Clearance::SessionsController#new
undefined method `signed_in?' for #<Clearance::SessionsController:0x007f44200273b0> Did you mean? sign_in_url
```

What could be the issue?

**Comment by derekprior** [comment]
Did you run `rails generate clearance:install`? Do you have `include Clearance::Controller` in your `ApplicationController`? This is what makes those helpers available in your controller.
