### ISSUE TITLE
recipe for api authentication?

### ISSUE THREAD

**Issue by jjb** [thoughtbot/clearance#708]
Is there a supported or recommended way to implement token authentication for apis?

I would like to detect an incoming token in a header and set current_user based on that.

I would like some, but not all, controller actions to be able to be accessed via either cookie auth or token auth.

If you point me in the right direction I'll submit a PR for documentation improvements (or add a wiki page).

Thanks!

**Comment by derekprior** [comment]
I've not done this with Clearance, so I won't be of much help. If you do accomplish this and want to write something up in the wiki, I'd appreciate it. We may then be able to make whatever steps were necessary simpler.

My hunch is that I would separate the idea of sign in as a user from authenticate via API with a token. I'd build token auth separately, overriding `current_user` to do `super || auth_with_token` or something like that.

**Comment by jjb** [comment]
@derekprior here's the approach I took https://github.com/thoughtbot/clearance/wiki/API-Authentication
