### ISSUE TITLE
config.allow_sign_up = false - still allows sign_up?

### ISSUE THREAD

**Issue by nickooolas** [thoughtbot/clearance#711]
Hey there,

Was looking to clarify what exactly the `config.allow_sign_up = false` actually does.

I had setup Clearance on a new app, I admittedly had installed all the views using the Clearance generator.

I noticed when I set `config.allow_sign_up = true` to `false`, it still allowed sign_up's on the /sign_up path.

What is the intent of this flag in config?

**Comment by magikid** [comment]
Are you using the default routes provided by Clearance or have you added the routes to your own `config/routes.rb` file?

**Comment by nickooolas** [comment]
Using the ones installed by Clearance after running install (install dumped all of them into the routes file)

**Comment by derekprior** [comment]
allow_sign_up only impacts clearance's internal routes. If you have dumped the routes to your local routes file you can remove the route from your routes file if you'd like. The documentation states that the `allow_sign_up` setting is ignored when (clearance internal) routes are disabled.
