### ISSUE TITLE
Strict Mode Email Validation blocks new TLD Addresses

### ISSUE THREAD

**Issue by hhff** [thoughtbot/clearance#712]
The new TLD style emails (`hugh@sanctuary.computer` for example) is not considered valid by the `email_validator` when `strict_mode` is true.

What's the best move to allow emails formatted like this in Clearance?

**Comment by derekprior** [comment]
Are you sure? I looked quickly at the code for EmailValidator, which the validation uses, and enabling strict mode seems to have no impact on the regex used for the domain.

```
EmailValidator.regexp(strict_mode: true) =~ "hugh@sanctuary.computer" #=> 0
```

I also just updated clearance's `user_spec.rb` locally to add:

```
  it { is_expected.to allow_value("hugh@sanctuary.computer").for(:email) }
```

This passes. What made you suspect it was something to do with strict mode or even clearance?

**Comment by hhff** [comment]
Oh!  It may be a collision with a different lib in that case...  I'll keep looking!  Thanks @derekprior !
