### ISSUE TITLE
different behavior for api calls

### ISSUE THREAD

**Issue by jjb** [thoughtbot/clearance#713]
I'd like to "turn off" "auto-login" when my app is dealing with an api request. Currently if a client http library persists and sends cookies, clearance will actually authenticate a user before I do so with my api auth token scheme.

is there a way to specify that clearance only authorize a user via cookie for certain controller actions?

and/or, is there a way to selectively not send the remember token back with the response?

see also #708

**Comment by jjb** [comment]
(since everything is done deep in the bowels of a rack middleware I'm guessing there aren't a lot of options here without hacky monkeypatching and route pattern matching)

**Comment by derekprior** [comment]
There is not currently a super clean way to do this. Is there an environment where you'd expect an API client to automatically handle cookies like this but not want to use it? The only thing I can think of is AJAX requests from the browser?

One alternative is to inject your own middleware that unsets the cookie when present on, for instance, responses coming from a request to `/api/...`

**Comment by jjb** [comment]
>  Is there an environment where you'd expect an API client to automatically handle cookies like this but not want to use it?

we have a notion of a user having multiple Devices. the Devices send a secret token as authentication. on the server side we use `sign_in` when we detect a valid token.

if a Device record is deleted on the server side, the device itself might still try to make requests while sending both the cookie and the token. the server will authenticate the user based on the cookie (which we don't want).

this was all designed with the assumption that non-browser clients don't persist and send cookies, which in my career i've never encountered until recently, apparently this is standard in macos/ios. we could actually redesign the system to not use tokens at all and rely on cookies.

(bit if a discussion tangent there)

okay so thanks @derekprior for your response, i'll close this ticket.
