### ISSUE TITLE
undefined method `[]' for nil:NilClass in Clearance::PasswordsController

### ISSUE THREAD

**Issue by sonalkr132** [thoughtbot/clearance#715]
Following passwords controller test fails with `NoMethodError: undefined method`[]' for nil:NilClass`:

``` Ruby
  context "when missing a parameter" do
    should "return bad request" do
      post :create
      assert_response :bad_request
    end
  end
```

It is coming from following [method accessing params](https://github.com/thoughtbot/clearance/blob/75e33bb0d0cd42aa97345d3496fd9e3e3ab73a05/app/controllers/clearance/passwords_controller.rb#L81) directly:

``` Ruby
  def find_user_for_create
    Clearance.configuration.user_model.
      find_by_normalized_email params[:password][:email]
  end
```

I have suggested following override in our app:

``` Ruby
  def find_user_for_create
    Clearance.configuration.user_model
      .find_by_normalized_email password_params[:email]
  end

  private

  def password_params
    params.require(:password).permit(:email)
  end
```

**Comment by sonalkr132** [comment]
Found another one [here](https://github.com/thoughtbot/clearance/blob/master/app/controllers/clearance/passwords_controller.rb#L75l).
```Ruby
def password_reset_params
    if params.has_key? :user
      ActiveSupport::Deprecation.warn %{Since locales functionality was added, accessing params[:user] is no longer supported.}
      params[:user][:password]
    else
      params[:password_reset][:password]  <- here
    end
  end
```
It gets called from `Clearance::PasswordsController#update`. Would you be accepting PR for this?
I think `find_user_for_create` could use a fix like b8a51add395c3374c54d4e47c0f013f786edff8b and `password_reset_params` can use strong param. Also, can [this](https://github.com/thoughtbot/clearance/blob/master/app/controllers/clearance/passwords_controller.rb#L72) depreciation be removed?

**Comment by derekprior** [comment]
If you would like to try to update submit a PR for these, please feel free to do so. However, please keep in mind that Clearance 1.x has support for Rails back to 3.1 so strong params are not an option. Also, the highlighted deprecation cannot be removed in 1.x.

**Comment by derekprior** [comment]
See #732
