### ISSUE TITLE
Layout configuration via initializer deprecated?

### ISSUE THREAD

**Issue by joshuajansen** [thoughtbot/clearance#719]
It seems that the layout configuration via an initializer isn't supported anymore? (https://github.com/thoughtbot/clearance#layouts)

I can't get it to work with an out-of-the-box implementation of Clearance `1.15.1` And while looking through the latest source, I couldn't find any references to this configuration.

Is it deprecated or are there any prerequisites for this configuration that I could've missed?

Thanks!

**Comment by derekprior** [comment]
This doesn't use any bit of Clearance, but rather uses a controller's public interface for changing the layout. You may need to restart your server after making this change?

**Comment by joshuajansen** [comment]
Ah right, that makes sense. Not sure why this is not being picked up for my app then. Closing this, thanks!

**Comment by michiels** [comment]
@joshuajansen Nice to see you here ;) Did you figure this out? Can't make it work myself.

**Comment by joshuajansen** [comment]
@michiels I'm not 100% sure anymore, but I think it had something to do with the way I set up template inheritance. If I remember correctly, this was solved by not prepending the view path when the current controller is a Clearance controller.

**Comment by michiels** [comment]
@joshuajansen ah ok thanks! Not doing template inheritance or view path modifying here. So maybe it's something else.

**Comment by jvanbaarsen** [comment]
@joshuajansen / @michiels I think I found the solution. Instead of putting it in an initialiser you should put it in `config/application.rb`, then wrap it inside a `config.to_prepare do` block.

This is my `config/application.rb`:

```ruby
module MyApp
  class Application < Rails::Application
    config.load_defaults 5.1

    config.to_prepare do
      Clearance::PasswordsController.layout "login"
      Clearance::SessionsController.layout "login"
      Clearance::UsersController.layout "login"
    end
  end
end
```

I created a PR to update the README.
