### ISSUE TITLE
why redirect with token in session?

### ISSUE THREAD

**Issue by jjb** [thoughtbot/clearance#726]
here in `PasswordsController`: https://github.com/thoughtbot/clearance/blob/master/app/controllers/clearance/passwords_controller.rb#L33-L35

when the user comes in with their reset link from their email that has `token=a1b2c3d41` in it, the user is redirected back to the same page with that token in the session instead.

Why is this done? something to do with keeping tokens out of caches / histories?

It's a problem for me right now because my url for a user's password change is `/profile/password/edit?token=a1b2c3d4&user_id=123`, so this action redirects the user to a url that doesn't have the user_id. I'm going to have to monkeypatch that controller action to fix this. Not a big deal but wanted to check in on the motivation behind the behavior first.

Thanks!
John

----

vaguely related: https://github.com/thoughtbot/clearance/issues/615

**Comment by jjb** [comment]
clearance by default requires user_id for looking up the user, even if/though the token is unique

https://github.com/thoughtbot/clearance/blob/master/app/controllers/clearance/passwords_controller.rb#L79

there's nothing in the clearance user model or migration that makes confirmation token guaranteed to be unique, so this is in fact necessary.

yes, i'm easily overriding the controller action for my needs.

```ruby
  def edit
    @user = find_user_for_edit

    if params[:token]
      session[:password_reset_token] = params[:token]
      redirect_to url_for(user_id: params[:user_id])
    else
      render template: 'passwords/edit'
    end
  end
```

the addition is `(user_id: params[:user_id])`

what clearance proper can possibly do to accommodate my need and other future scenarios is strip token from GET params and add then into the redirect.

**Comment by derekprior** [comment]
@jjb I can't think of a reason why there's no unique constraint on the indexes for `confirmation_token` and `remember_token`, but through normal use those tokens are generated via `SecureRandom` which is documented as suitable for "session key in HTTP cookies, etc". 

I'd still feel better if there were unique constraints though. PR welcome!

**Comment by abunashir** [comment]
@derekprior I was going through the implementation for the password reset feature, and couple of things came in my mind. The first one is adding the `user_id` in the password reset link. I don't have a very good reason why not to use it but I was considering

- It's the only place we are exposing internal `user_id` that we used to store that specific user
- It might give a rough estimation about the `user base` for an application (how? Maybe create a new account then try to reset the password and there is the last id )

And the another one is related to the `token`,  I completely agree with you, the possibility for a duplicated `token` is virtually zero. And we are also removing each `confirmation_token` as soon as a user resets their password, So I wouldn't worry about it, but if that make us feel better then sure we can do that too :). This [stackoverflow thread](http://stackoverflow.com/a/18564387/6819681) might be helpful.

I am not totally sure if we need to consider those factor or not, but if that's the case we can do something similar to

- Generate a unique `confirmation_token` (I'm happy with the existing way it is, but just in case we want to be 100% sure and can accept the debt of performing couple of database query to verify it's uniqueness)

- Change the `Password Reset Link` structure to `/password/edit?token=[token]` or `/passwords/[token]/edit` and use the `token` to identify the `user`.

- Based on the `url` structure, we can adjust the `edit` / `update` action.

Thanks for taking the time, Please let me know your thoughts, and if it's desirable, then I would be more than happy to put those together in a PR.

Inspiration:

- [Devise Implementaiton](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/passwords_controller.rb#L23)
- [Devise's token generation](https://github.com/plataformatec/devise/blob/master/lib/devise/token_generator.rb#L14)

**Comment by derekprior** [comment]
I believe the why has been answered sufficiently here. I don't think user id needs to be in the reset link, but changing this now would likely be a breaking change.

I would accept a PR to the migrations that adds a unique constraint to the database.
