### ISSUE TITLE
feedback when submitting empty email address for password change

### ISSUE THREAD

**Issue by jjb** [thoughtbot/clearance#727]
if a user submits an empty or invalid email address, the behavior to them is the same as if they submitted an email address

https://github.com/thoughtbot/clearance/blob/master/app/controllers/clearance/passwords_controller.rb#L22-L28

i'm guessing that this is partly to disallow a malicious person from checking a dictionary of email addresses for existence.

but how about in the case of a blank submission? should we give a flash message and send the user back to the form?

if this desirable, i can put together a PR.

**Comment by molfar** [comment]
I also notices this trouble. And I think it is irremissible.

**Comment by mjankowski** [comment]
Dupe of https://github.com/thoughtbot/clearance/issues/601
