### ISSUE TITLE
return_to loses anchor

### ISSUE THREAD

**Issue by MSchmidt** [thoughtbot/clearance#733]
I'm trying to redirect a user to a specific anchor after sign in by setting ``session['return_to']`` to something like ``/page#section``. The anchor gets dropped by this line though:

https://github.com/thoughtbot/clearance/blob/d72696fc6d32cdee219e64d392141eb1cda1ab3b/lib/clearance/authorization.rb#L98
```ruby
"#{uri.path}?#{uri.query}".chomp('?')
```

**Comment by derekprior** [comment]
The anchor, or fragment as it is know. In specs, supplied by a client is not sent to the server. The server isn't dropping this information, it just never received it. Fragment evaluation is handled on the client entirely.

**Comment by derekprior** [comment]
Ah, I see now that you are explicitly setting the fragment on the server, is that correct? If so then this is indeed a bug.

**Comment by MSchmidt** [comment]
Thanks for looking at this and sorry for the half baked description. I'll try to explain this a little better.

I'm setting ``return_to`` on the server to force a specific redirect after sign in.

```ruby
class SessionsController < Clearance::SessionsController
  def new
    session['return_to'] = params[:return_to]
    super
  end
end
```

At some places on the website I have sign in buttons with links like this: ``/account/sign_in? return_to=/raffles#raffle-form``. So users don't end up on their account pages after sign in (which is the default for regular sign ins). The redirect itself works fine, but the ``#raffle-form`` gets lost. It is stored in ``session['return_to']``  correctly though.
