### ISSUE TITLE
Can't alias password attribute

### ISSUE THREAD

**Issue by jmh** [thoughtbot/clearance#736]
I'm working on an admin screen in Rails 5 where I need a user's email and password fields not to autofill. My strategy for this with Devise was to do `alias_attribute :secret, :password` and use the name `secret` in the form. This worked well with Devise, but is failing with Clearance.

When I add the same alias to a model that uses Clearance I get the following error:

```
ActionView::Template::Error (undefined method `password_came_from_user?' for #<User:0x007fc2ef630100>
Did you mean?  secret_came_from_user?):
```

Ultimately I was able to work around this by adding a few methods to my model, but it feels bad (and wasn't needed when I used Devise, albeit that was Rails 4):

```(ruby)
alias_attribute :secret, :password
def password_came_from_user?; true; end
def password_before_type_cast; password; end
```

I wasn't able to find what's causing the different behavior for the two libraries. It would be great to be able to alias password cleanly. Chrome has become super aggressive at auto-filling and this is by far the cleanest method I've found to prevent it.

**Comment by derekprior** [comment]
Clearance doesn't do much custom with the `password` field. It's mostly just a glorified `attr_accessor` with a tiny bit of code that tells rails that the `encypted_password` field changes when someone uses the `password=` setter. We certainly don't do anything with the two methods you are overriding and I wouldnt recommend doing that.

If you want to call the password field soemthing else on the front end, I'd strongly encourage you to limit that difference to the front end, and not propagate it through your system. Use your controller to assign `params[:user][:secret]` to `user.password`, for example.
