### ISSUE TITLE
SSL as the default?

### ISSUE THREAD

**Issue by coreyward** [thoughtbot/clearance#738]
I'm giving Clearance a shot for the first time since I'm using Administrate. I typically `force_ssl` on any controllers that deal with sessions and allow non-users to peruse without https. Unfortunately, Clearance makes this really difficult. In order to do this, I'd need to go from a completely vanilla install to:

- Create `PasswordsController`, `SessionsController`, and `UsersController` in my app
- Either `force_ssl` on each of them, or insert an intermediary between the relevant ancestors and these app-specific controllers
- Override all of the routes provided by Clearance automatically to point to these new controllers
- Generate all of the views provided by Clearance

At which point, I may as well have just rolled my usual with `has_secure_password`. 

Is there a philosophical or technical reason that Clearance doesn't either 1) make `force_ssl` the default in Production on all Clearance routes or 2) provide a configuration option to do so?

**Comment by derekprior** [comment]
You should configure your Rails application to use `config.force_ssl` which will use SSL application wide, cause all cookies to be upgraded to "secure", etc. It doesn't require changing any routes or overriding any controllers.

I think this is beyond the scope of what clearance should do for you, as it's difficult to get right for development. I want to avoid as many situations as possible where something Clearance does causes your site to work in development but fail in production. I also want Clearance to be as secure as possible by default, so this is difficult.

There's some earlier discussion of this here: https://github.com/thoughtbot/clearance/pull/423

**Comment by coreyward** [comment]
That makes a handful of assumptions that, though right for many apps, are not right for the types I frequently build. Suffice to say that 99.5% of traffic to this site will be from non-users who never have an opportunity to share so much as an email address. Clearance sessions are only for admin users, of whom there will be maybe 5 total.

While I can't say that Clearance should/should-not do any particular thing for me, I do think that a Rails-integrated authentication library would be wise to not make using the options Rails provides out-of-the-box a chore. The `force_ssl` feature (in controllers) is not an anti-pattern.

The reason against upgrading all requests is that it has a measureable impact on page-rendering times, especially when a dozen or more assets across 3–5 hosts have to get upgraded to SSL. I like free performance wherever I can get it.

**Comment by jferris** [comment]
For a philosophical reason: a number of us feel pretty strongly that SSL should be enabled everywhere, all the time. We've written this up in our [guides](https://github.com/thoughtbot/guides/tree/master/security#application-security). We also have `force_ssl` set to true in production in our [app template](https://github.com/thoughtbot/suspenders).

**Comment by derekprior** [comment]
> The force_ssl feature (in controllers) is not an anti-pattern.

Anti-pattern or not, there are a number of things to consider when using the controller version of `force_ssl` that you do not need to consider when using SSL on all requests via the middleware. The middleware helps avoid common mistakes such as forgetting to mark cookies as secure and also sets [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) headers that ensures future connections from that browser will use HTTPS by default when no protocol is specified. The controller version of `force_ssl` is a shortcut for a before_action that does a redirect.

> I like free performance wherever I can get it.

Not to be a jerk, but nothing is free. Insecure HTTP requests have a real cost. Perhaps their cost (MITM, disclosure of user activity, etc) is one you are willing to accept, but it is not free.

If you'd like to use `force_ssl` in controllers, you can do so by re-opening `Clearance::BaseController` and adding `force_ssl` there. That was the purpose of introducing that base class.

**Comment by coreyward** [comment]
Thank you for the additional information, @derekprior. 

I certainly agree that it's a smart default, and that a majority of applications benefit from it. For those applications that don't, judicious use of `force_ssl` with secure cookies (fairly easy to do if you configure the session store appropriately) works well. 

I appreciate you calling out the solution using `Clearance::BaseController`. That would have solved my problem and avoided an unfortunate conversation with a client last week.
