### ISSUE TITLE
SignInGuard doesn't receive failed login attempts

### ISSUE THREAD

**Issue by davidferril** [thoughtbot/clearance#742]
I want to catch failed login attempts and log them to disable accounts for a tmie.

`class FailedAttemptGuard < Clearance::SignInGuard

  def call
    puts "SIGNED IN: #{signed_in?}"
    next_guard
  end

end`

the function never gets called if the user fails to log in. i'd like to catch that but i'm unable to with guards. is there another way to execute some code on login failure?

**Comment by magikid** [comment]
I think the preferred way for modifying that behavior is to subclass the [SessionsController](https://github.com/thoughtbot/clearance/blob/master/app/controllers/clearance/sessions_controller.rb). That would give you much finer control over the behavior on failed login.

**Comment by davidferril** [comment]
thanks @magikid, that worked out well!
