### ISSUE TITLE
Don't unconditionally forward the authentication token

### ISSUE THREAD

**Issue by rogercampos** [thoughtbot/clearance#744]
I found a problem while using clearance and I want to know your opinion on this before doing any PR. I see here that the authentication token received in the request is unconditionally forwarded in the response:

https://github.com/thoughtbot/clearance/blob/master/lib/clearance/rack_session.rb#L24

Since this behavior is in a middleware, it affects the application as a whole. If the application implements http caching in some endpoint, setting `Cache-Control: public` to allow for intermediary caches to do their job, this behavior will lead to leaked authentications.

This is unexpected from the developer point of view, since this happens even if the `Clearance::Authentication` module is not included anywhere in the controller stack. Not to mention a potential security issue.

**Comment by derekprior** [comment]
This is being discussed in the related PR #753
