### ISSUE TITLE
failing to reset your password breaks password reset indefinitely

### ISSUE THREAD

**Issue by eostrom** [thoughtbot/clearance#749]
Using Clearance 1.16.0 (and Rails 5.1.2, although I don't think it matters). Steps to reproduce:

1. Request a password reset.
2. Click the link in the email. You will see the new password form. DO NOT CHANGE YOUR PASSWORD.
3. Request a second password reset.
4. Click the link in the second email.

You should see the new password form again, but instead you will see the password reset email address form, with a message that says "Please double check the URL or try submitting the form again."

You can double check the URL and submit the form all you want, but password reset will remain broken until you clear cookies for the site.

(Step 2 – clicking the link but not bothering to fill out the form – is something of an edge case. We had a user who couldn't change her password due to an unrelated bug. But a browser could crash, a user could get distracted, etc. It shouldn't doom them forever.)

The cause of the bug: `PasswordsController#edit` stores the reset token in the session cookie. The token isn't deleted unless `PasswordsController#update` succeeds. And `find_user_by_id_and_confirmation_token` uses the token from the cookie, *even if there's a new token in the URL*.

A fix: Prefer the token in the URL over the one in the cookie. I believe this would fix all the use cases I've thought of, and I see no down side:

```
token = params[:token] || session[:password_reset_token]
```

**Comment by gduquesnay** [comment]
This is happening on our app also.  Waiting on this issue to be fixed so we can update clearance.  I'm assuming 

```
token = params[:token] || session[:password_reset_token]
```

mentioned above is something to be changed inside clearance code.  Is there a workaround that we can use in the meantime while we wait for this to get patched by clearance?

**Comment by abunashir** [comment]
@eostrom, @gduquesnay: I have created a PR with your suggestion and that should fix the issue, but in the meantime, you can also [override the password controller](https://github.com/thoughtbot/clearance#overriding-clearance) with the following code to fix the issue

```ruby
class PasswordsController < Clearance::PasswordsController
  private

  def find_user_by_id_and_confirmation_token
    user_param = Clearance.configuration.user_id_parameter
    token = params[:token] || session[:password_reset_token]
    
   Clearance.configuration.user_model.
      find_by_id_and_confirmation_token params[user_param], token.to_s
  end
end
```
