### ISSUE TITLE
Request Spec Helpers

### ISSUE THREAD

**Issue by dwightwatson** [thoughtbot/clearance#752]
Hey there, thanks for this library - I'm a big fan.

Clearance has an authentication BackDoor for feature specs as well as helpers for controller specs, but it doesn't have anything for request specs.

I was was wondering if that's something you would consider supporting or if there is a reason that request spec helpers have been omitted. It [seems as though the Rails and RSpec communities](http://rspec.info/blog/2016/07/rspec-3-5-has-been-released/) have been moving towards request specs to replace controller specs.

I've been using this code (which I'll break out into a helper) in order to authenticate in my request specs but hoped there would be a better way.

```
let(:user) { create(:user, password: 'password') }
 
before do
  post session_path, params: { session: { email: user.email, password: 'password' } }
end
```

Thanks!

**Comment by derekprior** [comment]
I haven't tested this, but I believe the back door should work in request specs as well?

**Comment by derekprior** [comment]
Closing this for now. If you find the backdoor does not work in request specs, please let me know and I'll re-open.

**Comment by dwightwatson** [comment]
It doesn't appear to work in request specs. I've got the `Clearance::BackDoor` middleware registered in my `test.rb` environment file, and I've required `clearance/rspec` in my `rails_helper.rb` file. The helpers work fine in controller tests, but the methods aren't available for request specs - including `sign_in` and `sign_in_as`.

```rb
  1) Agreements user access GET #new returns a successful response
     Failure/Error: before { sign_in_as user }
     
     NoMethodError:
       undefined method `sign_in_as' for #<RSpec::ExampleGroups::Agreements::UserAccess::GETNew:0x00007fcd67f60158>
     # ./spec/requests/agreements_spec.rb:28:in `block (3 levels) in <top (required)>'
```

Hope this provides enough information, happy to provide more if helpful. Thanks for your response.

**Comment by dwightwatson** [comment]
Hey @derekprior any update on this one? You didn't re-open the issue so I assume you might not have seen the earlier comment.

It might be worth considering adding a backdoor for system specs as well now they're available in Rails 5.1 and RSpec 3.7.

**Comment by derekprior** [comment]
`sign_in` and `sign_in_as` are controller helpers. To use the backdoor, you pass the `as` parameter to your path helper, like so:

`get agreements_path(as: user)`

**Comment by dwightwatson** [comment]
Ah, of course. Thank you for your help!

**Comment by Aiderlei** [comment]
Would be nice to add this to the doc under "Testing" as an own heading on Request Specs. Thanks! :)
