### ISSUE TITLE
CI environment tests failing...

### ISSUE THREAD

**Issue by justrudd** [thoughtbot/clearance#771]
This is probably not the appropriate place to ask. So please direct me towards a mailing list or slack channel or whatever.

Clearance is working great. My app works, people can login, etc. Rspec helpers work great. I've got a mixture of feature tests - some using Selenium web driver (Chrome in headless mode) and some using Rack Test. Everything works great running locally on my Mac.

But when I try to run my tests via CircleCI (or Heroku CI), anything that tries to hit a Clearance controller dies. So a request is routed to SessionsController#new, the logs show...
   Rendering new.html.erb in layout application.html.erb
   Rendered new.html.erb in layout application.html.erb
   500 returned

On my local, I see the following...
   Rendering new.html.erb in layout application.html.erb
   Rendered _form.html.erb
   Rendered new.html.erb in layout application.html.erb
   200 returned

On CI systems, it isn't trying to render the form partial. It just dies. I removed the render partial, and it still dies. I have other tests that don't require hitting any Clearance controllers, and those tests pass as expected.

So I'm not sure where to go from here. I don't believe this a Clearance issue, but it is only the Clearance controllers that are causing everything to die. And only in a CI environment.

**Comment by ChrisCPO** [comment]
@justrudd I'm seeing a similar issue. However locally, I have not tried on Semaphore. 
What is happening for me is 1st route visited in specs works then when a link is clicked that also requires authentication they are redirected to SessionController#new. I put a `binding.pry` in the `require_login` method and check for a current user. On 2nd request the current_user is missing.


"chromedriver-helper", "~> 1.2.0"
"selenium-webdriver", "~> 3.13.0"
"rails", "5.2.1"
"clearance", "~> 1.16.1"

**Comment by mjankowski** [comment]
@justrudd - is this still an issue? If you resolved it, can you share details?
