### ISSUE TITLE
Unable to login as admin in IntegrationTest

### ISSUE THREAD

**Issue by msk999** [thoughtbot/clearance#772]
This might have been addressed in later versions of Rails.  I am using rails 4.2.7.  I have a test class that descends from ActionDispatch::IntegrationTest.  the login method is as follows:    

```
def login_as(user)
  request.env[:clearance].sign_in(user)
end
```

Here's a snippet of the IntegrationTest

```
class SlavesAdminTest < ActionDispatch::IntegrationTest
  let(:admin) { create(:admin) }
  before do
    @slave = create(:slave)
    login_as(admin)
  end
  describe 'batch actions' do
       ...  doesn't get this far.  Exception is raised in the login_as method
  end
```

Using IntegrationTest the request object is nil causing an exception

I have another test that does not descend from IntegrationTest which works fine.  By the time it gets into the login_as method there is a request object and everything works fine.

I tried to figure out when the request object is instantiated when using that test, but it's not obvious and is time consuming to trace through.

Here is a snippet of test code that is working

```
describe 'Admin::SlavesController' do
  let(:admin) { create(:admin) }
  before do
    @slave = create(:slave)
    login_as(admin)
  end

  it 'renders the slave page' do
    get :index
    assert_response :success
  end
```

Any assistance would be greatly appreciated and please let me know if you need additional code.
Thanks!

**Comment by mjankowski** [comment]
There is some discussion of and alternate solutions to this here https://github.com/thoughtbot/clearance/pull/783

The gist of it is to actually perform the sign in steps from within integration tests.
