### ISSUE TITLE
Duplicate error messages with User model validations

### ISSUE THREAD

**Issue by jmknoll** [thoughtbot/clearance#774]
This isn't a bug with clearance, but rather an issue with the default settings that should be mentioned in the documentation.

Due to the default email and password validations in the clearance User model, if the User validates writes common email or password validations, they will get duplicate errors on object.errors.all. For example, the following code:

```
class User < ApplicationRecord
  include Clearance::User

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end
```

Will produce the following errors:

`ActiveRecord::RecordInvalid: Validation failed: Email has already been taken, Email has already been taken, Password can't be blank, Password can't be blank`

After a bit of digging, it seems that this is because the clearance User module has a number of default validations. This is addressed in a comment in clearance's User.rb, but since this forcing users to abandon what is, IMO, a pretty standard rails practice, I think its probably worth mentioning the default settings in the documentation as well.

Apologies if its already there, I didn't notice it when I read through.

**Comment by mjankowski** [comment]
Resolved by https://github.com/thoughtbot/clearance/commit/dfeee787d876fb6727442bf936d0160e6dca514e
