### ISSUE TITLE
Can we add a configuration within clearance to point to the parent controller?

### ISSUE THREAD

**Issue by sithara** [thoughtbot/clearance#777]
Hi
I'm using Rails 5 in api mode and would want all my clearnace controllers to inherit from AdminController instead of the default ApplicationController. Do we have anything similar to how devise addresses this issues:
config.parent_controller = 'AdminController'

Kind Regards
Sithara

**Comment by alex-benoit** [comment]
+1

**Comment by alex-benoit** [comment]
closing the loop on this https://github.com/thoughtbot/clearance/pull/867

**Comment by mjankowski** [comment]
Done in https://github.com/thoughtbot/clearance/pull/867
