### ISSUE TITLE
not using deliver_later?

### ISSUE THREAD

**Issue by jjb** [thoughtbot/clearance#790]
Hi,

I'm using clearance 1.16.1, rails 5.1, and Que 1.0.0.beta3. When I invoke a password reset email, I see this in my logs:

```
[ActiveJob] [ActionMailer::DeliveryJob] [7a9814be-ece9-41ee-a214-8c56395a1165] Performing ActionMailer::DeliveryJob (Job ID: 7a9814be-ece9-41ee-a214-8c56395a1165) from Que(default) with arguments: "ClearanceMailer", "change_password", "deliver_now", #<GlobalID:0x42 @uri=#<URI::GID gid://foo/User/42>> 
```

The readme suggests that this should be deliver_later, not deliver_now 

https://github.com/thoughtbot/clearance#deliver-email-in-background-job

Is something going wrong, or does the job actually invoke a deliver_now when executing?

Thanks!

**Comment by abunashir** [comment]
Hi @jjb, Unless you override the password controller or it's an earlier rails version then the password reset should use the `deliver_later` - [passwords_controller.rb#L60 - reset mail source](https://github.com/thoughtbot/clearance/blob/master/app/controllers/clearance/passwords_controller.rb#L60).

But for the actual mail devliery it would also be dependent on the adapter, for exmample the default `inline` adapter will  execute any job immediately. Thanks!

**Comment by jjb** [comment]
Thanks. So my question was, will the log line show deliver_now when the job worker works on it. Everything I'm seeing suggests that that is the case. Maybe this is more of a rails question than a clearance question :) I'll close this.
