### ISSUE TITLE
How to log in with command line curl?

### ISSUE THREAD

**Issue by jflat06** [thoughtbot/clearance#811]
Hi,

I am trying to log into my site using curl, and I'm having trouble correctly formatting a command correctly to do this.

So far I have tried: 

curl http://localhost:3000/session --data session[email]=user@example.com --data session[password
]=supersecretpassword --cookie-jar cookie.jar

This results in:

 ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)

I understand I need to somehow provide the token, but I'm having trouble finding any examples of how to do this. I see some examples with Devise, but they don't seem to work when applied to Clearance.

**Comment by mjankowski** [comment]
Did you figure this out - or still an issue?

Are you trying to just do a straight POST request without any previous requests to the site ... or are you running this command after first having requested the "new" (sign in) page?

Separately - if what you are trying to do is essentially "API access" via the command line with curl, you could set up a controller which disables the authenticity token (and optionally has some other requirement like a pre-shared API token)
