### ISSUE TITLE
1.16.2 Broke tests in ci environment

### ISSUE THREAD

**Issue by A-Scott-Rowe** [thoughtbot/clearance#825]
The check in the BackDoor code for `test` environment broke tests in the `ci` environment. Could there be a way to specify test environments? Perhaps with an environment variable.

**Comment by mjankowski** [comment]
Probably!

Just to be clear - you are running your tests on CI in an environment called `ci` - and thus the backdoor feature being disabled there (b/c it's not literally called `test`) is causing the problem?

I think your suggestion of expanding this check to be something like "if we are in the `test` environment OR `ENV['ENABLE_BACKDOOR']` is set to true, allow the backdoor" - might work. Is that what you meant?

**Comment by A-Scott-Rowe** [comment]
Yes, that's exactly right. 

I've currently got a monkey patch in the initializer as a workaround. 

Also, after thinking about it for a day or two an even better idea may be to add a new attribute to `Clearance.configure`. That should make it more clear what environments are explicitly for testing.

**Comment by mjankowski** [comment]
Fixed via https://github.com/thoughtbot/clearance/pull/830
