### ISSUE TITLE
Doesn't sign_out

### ISSUE THREAD

**Issue by afpava** [thoughtbot/clearance#826]
Hello!
 I notice that after sign_out action - session doesn't become empty. 
After some research I noticed that in controller `sessions` `destroy action` method sign_out is called - but there is no method all over related files. So I had to do monkey patch in my application_controller 
```
def sign_out
     session[:user_id] = nil
end
```

**Comment by mjankowski** [comment]
Can you clarify a little bit? There is a `sign_out` method defined in clearance internals.

Depending how you set up your controllers you may or may not ever need to call it directly.

**Comment by afpava** [comment]
Thank you for your answer!
I had my controller set to store user_id in a `session`, that's why I had that problem. 
Now I know that in `clearance` you store and check in `User` table.
Sorry for that dumb post. Please close that issue.

**Comment by mjankowski** [comment]
Glad it helped, thanks.
