### ISSUE TITLE
Allow Clearance::BackDoor in development environments

### ISSUE THREAD

**Issue by nsuchy** [thoughtbot/clearance#829]
I noticed the commit https://github.com/thoughtbot/clearance/commit/372c1514b892815914535d462409a354e1540964 restricts usage of `Clearance::BackDoor` to unit testing. Could this be modified to allow use in development environment, while this creates a security flaw in a production environment, it'd be useful for quickly switching between test accounts in development mode and is worth considering (as long as its kept off by default). Would a pull request be accepted for this change?

**Comment by mjankowski** [comment]
Yes, discussed here as well - https://github.com/thoughtbot/clearance/issues/825

I could see either of these approaches probably working:

- Expand the list of envs where its allowed to be any of: `test`, `development`, `ci`
- Allow configuration of allowed envs, default to those

**Comment by nsuchy** [comment]
I like the second approach better as it gives the developer more control. Could we just ask the developer to pass an array into the initializer and if `empty` or `nil` default to `test` and `development` and `ci`?

> Yes, discussed here as well - #825
> 
> I could see either of these approaches probably working:
> 
> * Expand the list of envs where its allowed to be any of: `test`, `development`, `ci`
> * Allow configuration of allowed envs, default to those

**Comment by mjankowski** [comment]
Fixed via https://github.com/thoughtbot/clearance/pull/830
