### ISSUE TITLE
current_user nil while using omniauth with clearance

### ISSUE THREAD

**Issue by sithara** [thoughtbot/clearance#837]
This is my sessions controller

```
class SessionsController <  Clearance::SessionsController
  include ActionView::Layouts
  include ActionController::Flash
  
  def create
    user = AdminUser.find_or_create_from_auth_hash(request.env['omniauth.auth'])
    sign_in(user)
    redirect_to admin_dashboard_index_path
  end
end
```
with the below code in AdminUser model

```
    def self.find_or_create_from_auth_hash(auth)

    a = AdminUser.where(email: auth.info.email).first
    unless a.blank?
      a.name = auth.info.email
      a.email = auth.info.email
      a.save!
    else
      a = AdminUser.create(name: auth.info.email, email: auth.info.email )
    end
    return a
end
```
for some reason my current_user is nil when redirected to admin_dashboard_index_path. I have `require_login` in all other controllers. So the AD login gets into an indefinite loop. Am I missing any configuration ? All my other controllers are inherting from AdminController which inherits from ActionController::Base

**Comment by sithara** [comment]
@mjankowski could you please suggest a workaround for persistinv the current_user value even while inherting from ActionController::Base?

**Comment by mjankowski** [comment]
You can read about what clearance does when you install it here: https://github.com/thoughtbot/clearance#getting-started

My guess is that you can include `Clearance::Controller` into your `AdminController` and get what you want?
