### ISSUE TITLE
Feature Specs Not Using Clearance::BackDoor and Session Token

### ISSUE THREAD

**Issue by coneybeare** [thoughtbot/clearance#841]
I'm not sure if this is the expected behavior, but I am having trouble with feature specs that involve multiple actions not using the session token to login through the backdoor.

I run a `visit path(as: xyz)` and can login fine through the Backdoor, but if my Capybara spec clicks on a link, that `as:` param is not passed through the params (as expected), but the session token is also not being used to authenticate the user. This means that in the dev or production scenarios, the same action sequence works by reading the stored session token, but this is not what I am seeing in my test environment using the Backdoor.

Clearance Version 1.17.0. Is this the expected behavior of the Backdoor?

**Comment by coneybeare** [comment]
Doing some further debugging, somehow the `remember_token_cookie` is lost in a single feature spec. I added a log to `Clearance::Session#cookies` to log the contents every time it is called. Here is a condensed log output showing the prob after a `#new` > `#create` form submit.

````
Started GET "/[REDACTED]/new/" for 127.0.0.1 at 2019-05-23 20:00:11 -0400
Processing by [REDACTED]Controller#new as */*
  Parameters: {"[REDACTED]_id"=>"medium-male-dingo"}
COOKIES: [["[REDACTED]_remember_me_token","b8352ca4571e6b899a9fe442cfc9abad4ca26ca2"]]
  User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."remember_token" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["remember_token", "b8352ca4571e6b899a9fe442cfc9abad4ca26ca2"], ["LIMIT", 1]]

Started POST "/[REDACTED]/medium-male-dingo.html" for 127.0.0.1 at 2019-05-23 20:00:13 -0400
Processing by [REDACTED]#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "messaging_service"=>{[REDACTED], "[REDACTED]_id"=>"medium-male-dingo"}
COOKIES: []
Redirected to https://localhost.test:63825/sign_in/
Filter chain halted as :require_login rendered or redirected
Completed 302 Found in 2ms (ActiveRecord: 0.0ms)

Started GET "/sign_in/" for 127.0.0.1 at 2019-05-23 20:00:13 -0400
Processing by Authentication::SessionsController#new as JS
COOKIES: [["_[REDACTED]_session",".....8O3nLoGDyQREIAB3Duls47096HlyngGlvipcPq7ahvXdp9/W+QzCI8=--LUNz1cjym+Ijmt2d--r82GaaL66JpnjM3pUmEI3A=="]]
Completed 200 OK in 25ms (Views: 23.6ms | ActiveRecord: 0.0ms)
````


What could be causing the `remember_token` to disappear mid-spec? Clearance, or something else?

**Comment by mjankowski** [comment]
Can you paste the (redacted if needed) feature spec?

Does this happen in just this one feature spec (out of many?) - if so, what's different/interesting about it?

This feels similar to the "configuring a custom domain for cookies" issue - are you doing that in the test env?

**Comment by coneybeare** [comment]
It doesn't happen on any particular feature spec, it seems to happen randomly, perhaps after a certain period of time(?). I agree it may be related to that custom domain issue, but my setup is pretty barebones for the test env:

Clearance setup
````
config.cookie_domain = nil
config.cookie_expiration = ->(cookies) { 1.month.from_now.utc }
config.cookie_name = '[REDACTED]_remember_me_token'
config.secure_cookie = false
````

Capybara driver setup
````
Capybara.register_driver :headless_chrome do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
    chromeOptions: {
      args: %w(headless disable-gpu),
      'profile.managed_default_content_settings.notifications': 2,
    },
    acceptInsecureCerts: true
  )
  
  profile = Selenium::WebDriver::Chrome::Profile.new
  profile["profile.default_content_settings"] = { images: '2' }

  options = Selenium::WebDriver::Chrome::Options.new(args: ['headless', 'window-size=1024,1024', '--blink-settings=imagesEnabled=false'])

  Capybara::Selenium::Driver.new app,
    browser: :chrome,
    desired_capabilities: capabilities,
    profile: profile,
    options: options
end
Capybara.javascript_driver = :headless_chrome
````

Capybara server setup
````
Capybara.server_host = 'localhost.test'
Capybara.server = :puma, {
  Silent: true,
  Host: "ssl://#{Capybara.server_host}?key=#{ssl_key_file}&cert=#{ssl_cert_file}"
}
````

puma config
````
ssl_bind 'localhost.test', 3000, {
    key: Rails.root.join('config','ssl', 'localhost.test.key'),
    cert: Rails.root.join('config','ssl', 'localhost.test.crt'),
    verify_mode: 'none'
  }
````

**Comment by coneybeare** [comment]
It may be related to [this SO question](https://stackoverflow.com/questions/36472930/session-sometimes-not-persisting-in-capybara-selenium-test) which has some insight in the comments by Capybara writer @twalpole -- I'm going to investigate

**Comment by coneybeare** [comment]
Sorry to file the bug, not clearance related at all. Fixed with the steps in this [SO answer](https://stackoverflow.com/a/51954685/69634) by none other than @twapole

**Comment by coneybeare** [comment]
Coming back to this in case future searchers need it, the SO Answer linked above helped make the tests faster, which made the real problem seem to go away, but the problem actually came back in extended tests. Turns out that a recent version of headless chrome has an acknowledged bug in which  [Cookies are randomly lost after 30 seconds while running headlessly](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2897)
