### ISSUE TITLE
Rails 6, custom user model and autoloading

### ISSUE THREAD

**Issue by matt17r** [thoughtbot/clearance#842]
I'm on Rails ~6.0.0rc2~ 6.0.0rc1 and Clearance 1.17.0 (and I'm using Minitest if that makes a difference).

I added `config.user_model = Person` to my Clearance initialiser but now when I run tests (using minitest) I get a deprecation warning that "Initialization autoloaded the constants ApplicationRecord and Person."

I also got that warning when I added `config.middleware.use Clearance::BackDoor` to my test environment configuration (as suggested by krsyoung in https://github.com/thoughtbot/clearance/issues/695), meaning I was getting the warning twice, but I've removed that for the time being.

Based on the warning in the docs (https://edgeguides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-initializers) I'm guessing they decided to start issuing a warning when initialisers trigger autoloading in Rails 6 but I'm not 100% sure how to check this.

It's also possible (and much more likely) that there is a bug in my code somewhere, rather than a conflict between this gem and Rails 6 but at this stage the app is very young and I don't think there's anything else that could be causing this.

**Comment by mjankowski** [comment]
I don't actually see rails 6.0.0.rc2 released yet ... can you clarify that?

For what it's worth, I've been attempting to keep a [rails 6 prerelease branch](https://github.com/thoughtbot/clearance/tree/rails-six-prerelease) up to date, and will review there and attempt to replicate the reported error.

**Comment by matt17r** [comment]
Whoops! You are of course right, 6.0.0rc1. Thanks for spotting that! :)

I found the error string in Rails: https://github.com/rails/rails/blob/master/railties/lib/rails/application/finisher.rb

Discussion about this change is in https://github.com/rails/rails/pull/35745

> Use cases include:
> [snip]
> - To set some class level configuration, e.g. SomeAPIServiceClass.backend = MyMockBackend. TBH I kinda hate that pattern as it trigger the eager loading of a ton of stuff, causing the app boot time to go though the roof. But at the same time I never figured any alternative pattern.

That's what Clearance is doing, if I understand correctly; letting the user specify a different class.

I was able to prevent the warning by requiring ApplicationRecord and my Person class at the top of the initialiser:

```
require 'application_record'
require 'person'

Clearance.configure do |config|
  # TODO Change the sender address
  config.mailer_sender = "reply@example.com"
  config.rotate_csrf_on_sign_in = true
  config.routes = false
  config.user_model = Person
end
```

Perhaps it's enough to change the README to reflect that?

I also saw in https://weblog.rubyonrails.org/2019/2/22/zeitwerk-integration-in-rails-6-beta-2/ that one can use `autoloader.preload("#{Rails.root}/app/models/#{leaf}.rb")` for STI situations. Perhaps something similar could be done in Clearance? `autoloader.preload("#{Rails.root}/app/models/#{config.user_model}.rb")`?

**Comment by mjankowski** [comment]
Thanks for that research ... and yeah I think either a) just note this in the README re: need for explicit requires with zeitwerk, b) change how we do that config loading (maybe similar to the "dynamic access point" example in the doc you linked, while still based partially on a config setting) in clearance.

I suspect that within the clearance spec suite itself we are only ever setting that config option in a place where everything is already loaded and so we are not seeing the warning. I'm not sure if this would generate one - but using that config option within the spec suite "dummy app" might be a nice addition (to see and then solve the warning) as well.

**Comment by matt17r** [comment]
FYI, I just re-added `config.middleware.use Clearance::BackDoor` in `config/environments/test.rb` and the requires workaround I mentioned above prevents this warning too.

(That might be obvious but I'm not super clear on the order everything gets loaded/run in Rails so I tested it)

**Comment by matt17r** [comment]
One other thing I read in [my research](https://edgeguides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-initializers) is that in dev Rails uses `Kernel#load` rather than `Kernel#require` so the file can be reloaded if the contents change.

In this context I assume that means your option (b) above is probably the better long term solution?

**Comment by rickychilcott** [comment]
What about making it `config.user_model = "Person"` instead and doing the constant lookup elsewhere? That's a common pattern elsewhere in Rails, some of the relation helpers use `class_name` attribute as a string.

See https://guides.rubyonrails.org/association_basics.html#self-joins

**Comment by rickychilcott** [comment]
This will also be a problem for custom guards. An array of class names (as strings) would solve this as well.

Since rc2 is out now, we're likely close to needing a solution

**Comment by rickychilcott** [comment]
I spent a little more time researching this.

ActiveRecord uses `safe_constantize` to load the `class_name:` constants. See https://github.com/rails/rails/blob/fd6648d5979df6e6daf9fa7eb1d01cd87922ae32/activerecord/lib/active_record/associations/builder/belongs_to.rb#L36 While this is the safest thing, I suspect we'd actually just want to call `constantize` instead to raise an exception if the class isn't found.

The problem with explicit requires is that it may break code reloading or introduce other bugs if the underlying classes aren't loaded by zeitwork.

Since this is only user_model and sign_in_guards, the change should be pretty easy.

https://github.com/thoughtbot/clearance/blob/master/lib/clearance/configuration.rb#L114-L116

could become:

```ruby
    # move @user_model = "::User" into the initializer
    def user_model
      @user_model.to_s.constantize
    end
```

And https://github.com/thoughtbot/clearance/blob/master/lib/clearance/session.rb#L147 becomes
```ruby
  guards = Clearance.configuration.sign_in_guards.map(&:to_s).map(&:constantize)
```

This should be backward compatible for existing users who have class names and will allow opting into using Zeitwork, but not forcing it.

There are some performance improvements to be made for `user_model`, but if you're ok with that approach, I can fork the `rails-six-prerelease` branch and try to add this functionality.

**Comment by rickychilcott** [comment]
FYI. Rails 6 has been released. Does this approach work for you @mjankowski?

**Comment by mjankowski** [comment]
I think that does work - thanks for the proposal. Feel free to start a PR for this based off the rails six branch (related, I will open a PR to merge that in shortly).

**Comment by odlp** [comment]
I've taken a first pass of a PR to resolve this for `user_model` here:
https://github.com/thoughtbot/clearance/pull/853

I haven't had time to address `sign_in_guards`, so perhaps someone else could take a look at that.

**Comment by mjankowski** [comment]
Closing this on the assumption that #853 and #862 are sufficient here.

**Comment by rickychilcott** [comment]
Thanks @mjankowski!
