### ISSUE TITLE
Correct process for properly importing large number of user accounts

### ISSUE THREAD

**Issue by jflat06** [thoughtbot/clearance#845]
I am porting 800k user accounts from an old mysql database into a postgresql database with clearance.

My original approach for this was to iterate over each account and create a new user from inside of Rails. This seemed to work, but was extremely slow (several days).

My new approach is to export the data from mysql to a csv, then import it using postgres's COPY FROM. This is much faster (several minutes), but two of the columns are problematic.

Setting both 'encrypted_password' and 'remember_token' were being handled for me in the slow approach, but I'm not sure what to do for them in the new one.

Is there some safe default value I can give these that won't be a security issue? 

For the 'encrypted_password', it doesn't need to match their old password. I am handling authentication with old passwords using a different scheme until they log in once, in which case it will update 'encrypted_password' and start using that. So really I don't even want this to be functional until it has been overwritten. 

Sorry for the long winded question - I know just enough about security to know that I should seek advice from more experienced people.

**Comment by mike-burns** [comment]
Can't give a detailed answer right now but instead some hints:

- Set the `encrypted_password` to a valid string but invalid encrypted password during the `COPY FROM`.
- Set `remember_token` to the empty string.
- After the users are in, resetting their password will set these correctly.

---

All that said, this is just changing the DBMS. You could continue to use the existing data as-is without resetting it. You can change the password strategy in Clearance to whichever you need (the default is bcrypt).

---

Sorry again that I can't give a more detailed response right now. Let me know if this sets you in a right direction, or whether I misunderstood entirely

**Comment by jflat06** [comment]
That's perfect! I wasn't sure if it was safe to use things like the empty string for the remember_token. 

I didn't want to keep using our old password strategy, as it is dated and insecure - we want to transition to a new system ASAP. 

For an invalid bcrypt password: 

https://en.wikipedia.org/wiki/Bcrypt#Versioning_History

From this, it sounds like as long as I don't start the encrypted_password field with $, it should properly not function, since all hashes start with a $ symbol to identify the algorithm. 

So I guess the empty string would work here, too?

Thanks again!

**Comment by mike-burns** [comment]
Empty should work, yup!

Note that I haven't tried this, so please report back on how it goes.

**Comment by mjankowski** [comment]
Closing on assumption that this approach helped you, feel free to re-open if not.
