### ISSUE TITLE
After login, make redirecting to url optional

### ISSUE THREAD

**Issue by worldofprasanna** [thoughtbot/clearance#863]
**Problem:**

We are using rails in the api only mode and after successful / invalid login, UI would take care of displaying the message. But after login clearance is sending status 302 back with / as the redirect url. In our case, this is not valid as it gets redirected to **http://our-domain/** whereas the application is running in https.

**Expected**

I was expecting a configuration to turn off the redirection functionality. But it is not there and as an alternate approach, I have to override the sessions controller with the similar behaviour like this,

```
class SessionsController < Clearance::SessionsController
  def create
    @user = authenticate(params)
    sign_in(@user) do |status|
      render json: { message: 'logged in' }, status: :ok if status.success?
      render json: { message: 'login failed' }, status: :unauthorized unless status.success?
      return
    end
  end
end
```

Any thoughts about making redirection optional using the config variables ? I am happy to raise a PR for it.

**Comment by worldofprasanna** [comment]
@mjankowski Thanks for the info. 

I checked the apis_controller_spec, but I couldn't figure out how I can use it for login requests. In my case, I just want to return a JSON response irrespective of login success/failure and avoid redirection. Please correct me if I overlooked something in the spec.

**Comment by mjankowski** [comment]
Sorry, to clarify here -- I think the conclusion of "the only way to do this and avoid the redirect is by overriding the method" is accurate.

I'm going to close this on the assumption that that's actually fine and desirable, and that clearance handling the basic browser/html auth situation correctly but making it possible to override for APIs and use the auth methods is acceptable.

If there are ways to make it easier to do that override, I'd definitely review those PRs. For example - maybe extract some methods from within `create` around what to do in the success/failure cases, in a way where you would not have to override all of `create`, but could just override those?
