### ISSUE TITLE
Undefined Method 'current_user' for controller class method 'render'

### ISSUE THREAD

**Issue by ChrisCPO** [thoughtbot/clearance#879]
Rails: 6.0.2
Clearance: 2.0.0

When I have include the ClearanceController method in my ApplicationContrller(or subclass of)
and I call 
`ApplicationController.render(partial: "foos/bar", assign: { current_user: User.first })`
 I recieve an error from 
`/home/chris/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/clearance-2.0.0/lib/clearance/authentication.rb:39:in 'current_user' `

The main issue here is that I can't add a helper method, I still get the above error:
```
def current_user
  @current_user ||= super
end
```

If I comment out the include, change the helper and assign the current_user in the render call everything works as expected.
```
class ApplicationController < ActionController::Base
  # include Clearance::Controller
  protect_from_forgery with: :exception

  def current_user
    @current_user
  end
end
```

This can easily be tested in the console.

A workaround is to create a RendererClass from `ActionController::Renderer` which may be a more pure way to achieve my goal but I still wanted to report this oddity.

**Comment by mjankowski** [comment]
Possibly related? https://github.com/thoughtbot/clearance/issues/848

Can you be a little more specific about what you're trying to do and how/where you're doing it? Also read through the linked issue and see if it's more or less the same problem.

**Comment by ChrisCPO** [comment]
After reading through the liked issues. It is related, I'm also rendering a template outside of the request/response cycle. However, Maybe I need to rephrase my issue because when using a controllers class method `.render` I should be able to assign the instance var `@current_user` via the assigns param in the render method.
`ApplicationController.render(partial: "foos/bar", assign: { current_user: User.first })`
Then add a helper: 
```
# app/helpers/user_helper.rb

def current_user
  @current_user ||= super
end
```
However, Clearance seems to override this helper_method as I get the error above:
`/home/chris/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/clearance-2.0.0/lib/clearance/authentication.rb:39:in 'current_user'`

A better title for this Issue might be **Clearance is not allowing a @current_user instance var to be set**

**Comment by mjankowski** [comment]
I don't think this is actually the problem, but as a small note here - in the code you pasted you are using `assign: ...` but I think you actually want to use `assigns: ...`.

That said, a few more things:

- Is your goal just to override the view helper `current_user` method, or to actually have clearance "sign in" a user? The `@current_user` ivar you might be setting in your view or controller is probably not the same one clearance is using internal to track the user. But you might be able to call `sign_in` to have clearance sign in a user (with the caveats of the linked issue about renderers).
- Can you paste the full error output you are seeing, and/or more of your code, and/or a minimal test case showing what you want to happen and how it's failing?

**Comment by mjankowski** [comment]
I'm going to close this on the assumption that my last comment, or the linked issue, might have helped resolve/explain this. If there's more to do here in terms of a bug fix or feature addition, re-open and comment please.
