### ISSUE TITLE
Unable to do intial setup locally

### ISSUE THREAD

**Issue by udaykadaboina** [thoughtbot/clearance#884]
I forked & pull the gem, trying to [setup](https://github.com/udaykadaboina/clearance/blob/master/CONTRIBUTING.md) clearance after downloading.

`.bin/setup` command gives following error:
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/Users/uday/Development/clearance/gemfiles/rails_5.0.gemfile' || bundle install --gemfile='/Users/uday/Development/clearance/gemfiles/rails_5.0.gemfile' --retry 1
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/Users/uday/Development/clearance/gemfiles/rails_5.1.gemfile' || bundle install --gemfile='/Users/uday/Development/clearance/gemfiles/rails_5.1.gemfile' --retry 1
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/Users/uday/Development/clearance/gemfiles/rails_5.2.gemfile' || bundle install --gemfile='/Users/uday/Development/clearance/gemfiles/rails_5.2.gemfile' --retry 1
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/Users/uday/Development/clearance/gemfiles/rails_6.0.gemfile' || bundle install --gemfile='/Users/uday/Development/clearance/gemfiles/rails_6.0.gemfile' --retry 1
The Gemfile's dependencies are satisfied
rake aborted!
LoadError: Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? sqlite3 is not part of the bundle. Add it to your Gemfile.
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:346:in `block (2 levels) in replace_gem'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:13:in `<top (required)>'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/connection_specification.rb:170:in `spec'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1054:in `establish_connection'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:51:in `establish_connection'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/railtie.rb:201:in `block (2 levels) in <class:Railtie>'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:72:in `class_eval'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:72:in `block in execute_hook'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/base.rb:327:in `<module:ActiveRecord>'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/base.rb:27:in `<top (required)>'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/railties/databases.rake:19:in `block (2 levels) in <top (required)>'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/bin/ruby_executable_hooks:24:in `eval'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
Gem::LoadError: sqlite3 is not part of the bundle. Add it to your Gemfile.
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:346:in `block (2 levels) in replace_gem'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:13:in `<top (required)>'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/connection_specification.rb:170:in `spec'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1054:in `establish_connection'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:51:in `establish_connection'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/railtie.rb:201:in `block (2 levels) in <class:Railtie>'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:72:in `class_eval'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:72:in `block in execute_hook'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/base.rb:327:in `<module:ActiveRecord>'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/base.rb:27:in `<top (required)>'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/activerecord-6.0.2.1/lib/active_record/railties/databases.rake:19:in `block (2 levels) in <top (required)>'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/bin/ruby_executable_hooks:24:in `eval'
/Users/uday/.rvm/gems/ruby-2.6.3@clearance/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => dummy:db:reset => dummy:db:drop => dummy:db:load_config
(See full trace by running task with --trace)

**Comment by mjankowski** [comment]
Good catch. The setup script attempts to set up a dummy app db which will be used during the test suite runs. At some point we moved the sqlite3 dependency out of the main gemfile and into the appraisals file because it needed to be dependent on which version of rails we're loading.

We could probably point the setup script at one of the appraisal gemfiles, since I don't think it matters really which one we use to make the db.

All that said -- if you've successfully gotten to that point in the script, you could just manually do something like `RAILS_ENV=test BUNDLE_GEMFILE=gemfiles/rails_6.0.gemfile bundle exec rake dummy:db:reset` and it would make the db.

**Comment by mjankowski** [comment]
We could also potentially move the db reset out of the setup script, and into a before suite setup step.

**Comment by udaykadaboina** [comment]
Thanks, that makes sense! I followed the workaround step you suggested and it worked.
