### ISSUE TITLE
How do I override Clearance default class to include a username and password_confirmation on signup?

### ISSUE THREAD

**Issue by ibraheemdev** [thoughtbot/clearance#895]
How do I override Clearance default class to include a username and password_confirmation on signup? I still want to signup by email, however, I want to add a username, and a password confirmation

**Comment by composerinteralia** [comment]
You can [override any controller](https://github.com/thoughtbot/clearance#controllers) in clearance by creating a subclass and overriding whichever methods you choose. It sounds like you may want to override the [`user_params`](https://github.com/thoughtbot/clearance/blob/c3da4f62a7300b177d3b7d02b246144f6d473372/app/controllers/clearance/users_controller.rb#L43-L45) method.

**Comment by composerinteralia** [comment]
I'm going to close this issue for now since you asked it quite a while back. If you still have the question and my comment doesn't address it then we can reopen this issue. Thanks!
