### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/clearance#902]
Does Thoughtbot use Pundit or Clearance::Constraints when handling user permissions?

I thought about using `constraints Clearance::Constraints::SignedIn.new { |user| user.editor? }` but noticed that users aren't redirected to the login page or given an error message.

**Comment by eebs** [comment]
Thanks for the issue @ACPK. Looking at the documentation, it looks like this will always result in a 404. I believe this is the expected Rails behavior. The [`constraints`](https://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Scoping.html#method-i-constraints) documentation mentions that if the constraint is not matched it will behave as though the route does not exist.

https://github.com/thoughtbot/clearance/blob/c3da4f62a7300b177d3b7d02b246144f6d473372/lib/clearance/constraints/signed_in.rb#L11-L19

If your desired behavior is to redirect the user I would suggest using Pundit or another authorization library to do so.
