### ISSUE TITLE
Tracking failed password attempts - Overriding and session controller and  lib/clearance/authentication.rb

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/clearance#903]
Is there a recommended way to get the user_id that's found in lib/clearance/authentication.rb when overriding the sessions controller?

The line ```@user = authenticate(params)``` only returns a user if the login is successful.  It would be nice to have the user_id of the failed login so I don't need to do another database call to implement security features (ex: lock account after x failed logins, prevent dictionary attacks, etc.).

    class Clearance::SessionsController < Clearance::BaseController
        before_action :redirect_signed_in_users, only: [:new]
        skip_before_action :require_login, only: [:create, :new, :destroy], raise: false
    
        def create
        @user = authenticate(params)

        # @user is only set if the login is successful. Need to run `find_by_normalized_email(email)` for a second time as it's run when called in `authenticate(parans)`.

        # failed_user = find_by_normalized_email(email)
        # failed_user.handle_failed_login if failed_user
    
    
        sign_in(@user) do |status|
            if status.success?
            redirect_back_or url_after_create
            else
            flash.now.alert = status.failure_message
            render template: "sessions/new", status: :unauthorized
            end
        end
        end

        ...

        # Code below is from lib/clearance/user.rb

        def find_by_normalized_email(email)
            find_by(email: normalize_email(email))
        end

        def normalize_email(email)
            email.to_s.downcase.gsub(/\s+/, "")
        end
    end

**Comment by mjankowski** [comment]
Is this for the case where there's been a valid email supplied, but an invalid password ... and you want to do some sign in attempt tracking for the User that was found, and/or a database ID connected to that user?

I don't think there's anything in the public controller api which has a method you could use to do this directly.

You could probably do something like `User.find_by_normalized_email(params[:session][:email])` - and at a minimum, the query generated here will probably be cached from the previous attempt. I haven't actually tested that but something like it might be slightly better than a totally new lookup, while falling short of using an existing/loaded value.
