### ISSUE TITLE
Testing with nested parameters appears to be broken in v2.3.0

### ISSUE THREAD

**Issue by dwightwatson** [thoughtbot/clearance#913]
I've discovered a regression in our app after upgrading Clearance from v2.2.1 to v2.3.0.

I believe this was introduced in #897 which re-builds the query after removing `as`.

Doing some looking around, it appears there is some wonky handling of nested attributes with Rack:
* https://github.com/rails/rails/issues/23997
* https://github.com/rack/rack/issues/951

I'm using RSpec and notice that the format of my nested attributes change (and break) one they're in the controller.

```rb
attributes = {agreement: {agrement_splits_attributes: [{id: 1, amount: 100}, {id: 2, amount: 200}]}}
patch tenancy_agreement_split_path tenancy, params: {agreement: attributes}
```

When inspecting the parameters inside the controller action, that first amount is split into it's own hash.

```
"agreement_splits_attributes"=>[{"id"=>"1"}, {"id"=>"2", "amount"=>"200"}, {"amount"=>"100"}]
```

Rolling back to v2.2.1 resolves this instantly.

**Comment by taniadaniela** [comment]
@dwightwatson if you use `patch tenancy_agreement_split_path tenancy, params: {agreement: attributes}, as: :json ` does it handles the params correctly?

**Comment by dwightwatson** [comment]
No - I get this error, which sounds like the Backdoor is kicking in.

```
     Failure/Error: patch tenancy_agreement_split_path tenancy, params: {agreement: attributes}, as: :json
     
     ActiveRecord::RecordNotFound:
       Couldn't find User with 'id'=json
```

I then added the missing parenthesis for the path method, and this problem goes away.

```rb
patch tenancy_agreement_split_path(tenancy), params: {agreement: attributes}
```

So this was actually an issue with my test code, passing the params incorrectly. Apologies for the noise and thank you @taniadaniela for pointing me in the right direction to find what was wrong.
