### ISSUE TITLE
redirect_url not working?

### ISSUE THREAD

**Issue by philsmy** [thoughtbot/clearance#914]
Maybe I am misunderstanding how this should work, but, I thought that the `redirect_url` would be visited after signup.

In `config/initializers/clearance.rb` I have set:

```
Clearance.configure do |config|
  config.routes = false
  config.mailer_sender = "contact@mydomain.com"
  config.rotate_csrf_on_sign_in = true
  config.redirect_url = "/thank_you"
end
```

But `/thank_you` is never visited after a signup (or any time).

I also created `app/controllers/users_controller.rb` with:

```
class UsersController < Clearance::UsersController

  private

  def url_after_create
    "/thank_you"
  end
end
```

Yet still `/thank_you` is never visited.

What needs to be done to actually get new users sent to a new page so we can track them in analytics?

**Comment by eebs** [comment]
Hi @philsmy, thanks for the question. After a user signs up, Clearance redirects using [`redirect_back_or`](https://github.com/thoughtbot/clearance/blob/fbaf5cf368bc6512c11251559c5ecb655276994f/lib/clearance/authorization.rb#L80-L83)

[https://github.com/thoughtbot/clearance/blob/fbaf5cf368bc6512c11251559c5ecb655276994f/lib/clearance/authorization.rb#L80-L83](https://github.com/thoughtbot/clearance/blob/fbaf5cf368bc6512c11251559c5ecb655276994f/lib/clearance/authorization.rb#L80-L83)

This will redirect back to the URL the user was originally attempting to access if they were attempting to access an action protected by `require_login`. If the user did not try and access an action protected by `require_login`, they will be redirected to the `redirect_url`.

If your application uses `require_login` for the entire application then the user will always be redirected back to the URL they initially attempted to visit.

**Comment by philsmy** [comment]
Ok. How can we direct a person to a thankyou page after signup, regardless of what will happen after a non signup login? Seems odd to me that 'url after create' does nothing!

**Comment by eebs** [comment]
The most straightforward way would likely be to [override ](https://github.com/thoughtbot/clearance#controllers) the `UsersController` [`create`](https://github.com/thoughtbot/clearance/blob/master/app/controllers/clearance/users_controller.rb#L10-L19) action and change

```
redirect_back_or url_after_create
```

to

```
redirect_to url_after_create
```
