### ISSUE TITLE
NameError: undefined local variable or method 'flash' for controller...

### ISSUE THREAD

**Issue by JonesGladston** [thoughtbot/clearance#915]
Hi all,
         Running clearance gem on my rails -API only application and getting this error while clearance is trying to show flash messages.

![image](https://user-images.githubusercontent.com/46124171/98245581-24a13700-1f97-11eb-9452-2689f3ca0520.png)

Is there any way to disable flash from clearance side??

**Comment by eebs** [comment]
Thanks for submitting an issue @JonesGladston. Clearance does not support API mode out of the box and we don't currently have any plans to offer an API only configuration option.
