### ISSUE TITLE
Changing user_model doesn't change routes in templates

### ISSUE THREAD

**Issue by stevenbuccini** [thoughtbot/clearance#918]
We changed our application's Clearance model to `Foobar` in the initializer. This changes a lot of things, including `Clearance.user_id_parameter`. To properly pull this value down, we needed to update our routes. However, when we updated our routes, the URL helpers in the views (for resetting passwords, for example) still point to routes that work for `user` namespaces. It seems like these should be generated dynamically with the value returned by `Clearance.user_parameter`

**Comment by eebs** [comment]
Hi @stevenbuccini, thanks for the issue. I was able to reproduce your issue by creating a new app, creating a Foobar model, and installing Clearance. I set `config.routes = false` in the Clearance initializer, and copied the routes from Clearance into the application's routes.rb file, replacing `resources :users` with `resources :foobars`.

I was able to navigate to all the sign up, sign in, and password reset pages, but when attempting to reset the password I got the error you mentioned. This happens as part of generating the password reset email.

```
undefined method `edit_user_password_url' for #<#<Class:0x00007ffce93b5b30>:0x00007ffce93b42d0>
Did you mean?  edit_foobar_password_url
```

When clicking the link in the password reset email, the page displays a similar error:

```
undefined method `user_password_path' for #<#<Class:0x00007feebf2e6778>:0x00007feec02f1960>
```

Were there any other places you noticed an issue with the routes?

---

I believe we can address this by using Rails' [polymorphic routes](https://api.rubyonrails.org/classes/ActionDispatch/Routing/PolymorphicRoutes.html). I'll try to get a PR up in the near future for this.

**Comment by stevenbuccini** [comment]
Thanks @eebs for the PR! I am glad you were able to repro. I discovered this error when attempting to reset passwords, so the places you identified were the only edits I had to make. Great idea to use polymorphic routes!

Thanks again for being proactive, I was happy to make the changes myself but wanted to get some feedback on the issue before I put a PR.

**Comment by eebs** [comment]
Ah sorry for jumping ahead a bit @stevenbuccini, I wasn't 100% sure the polymorphic routes were going to work and so in reproducing and testing them I ended up with the PR. Thanks for offering to help out though, it's really appreciated!

Would you be able to try out the [branch](https://github.com/thoughtbot/clearance/tree/ek-fix-password-routes) in your application? I couldn't think of a good way to test the changes via the specs but I did run through the flows manually a few times.

**Comment by stevenbuccini** [comment]
I pointed my `Gemfile` to your branch, removed the views I had generated and modified, and everything works! Thanks so much for the fix.
