### ISSUE TITLE
Creating A Separate Email Address Table

### ISSUE THREAD

**Issue by cht-wtag** [thoughtbot/clearance#927]
If we have a separate email address table named as **emails** and the association with the user is like `has_many: emails`

```
class User < ApplicationRecord
  include Clearance::User

  has_many :emails
  accepts_nested_attributes_for :emails
end
```
Is there any way we can create a user without an email filed and validate by an email(say primary) from the emails table?

**Comment by eebs** [comment]
This is not something Clearance supports out of the box. You might be able to override some methods to make it work but I'm not sure exactly how that would work.

**Comment by krtschmr** [comment]
The most straight forward would be to always have the primary email from your email table as a hard copy attribute inside your user table. 
your business logic won't update the user table, but whenever you update the emails table or set the primary flag, trigger a callback to update inside the user.
