### ISSUE TITLE
Incompatible with Turbo

### ISSUE THREAD

**Issue by dwightwatson** [thoughtbot/clearance#929]
It appears that Clearance is incompatible with Turbo out of the box, as Turbo will no longer render responses to forms **unless** they have a 4xx/5xx status.

* `UsersController#create` returns `render template: "users/new"` on a validation error - this may need to be updated to `render template: "users/show", status: :unprocessable_entity`
* `PasswordsController#create` returns `render template: "passwords/create"` regardless of whether a password reset has been sent or not - this may need to be updated to a redirect somewhere.
* `PasswordsController#edit` returns `render template: "passwords/edit"`without a token on the request - this may need to be updated with `:unprocessable_entity` also.

Adding `status: :unprocessable_entity` is an easy fix for two of these, and I wonder if perhaps `PasswordsController#create` and just redirect back to `PasswordsController#new` with a successful flash message.

Related: #925

**Comment by manuelmeurer** [comment]
Would love to see Turbo support added! I did the necessary changes in my fork: https://github.com/manuelmeurer/clearance/tree/turbo
Would a PR be acceptable? #936 is already open with most of the fixes.
