### ISSUE TITLE
Doc typo for config.httponly

### ISSUE THREAD

**Issue by unlimit** [thoughtbot/clearance#941]
Hi!
I found a small typo in the docs.
`config.httponly = false`
But **httponly** is actually set to **true** by the [default](https://github.com/thoughtbot/clearance/blob/master/lib/clearance/configuration.rb#L128).

**Comment by MottiniMauro** [comment]
Thanks for reporting this @unlimit !. I create a [pull request](https://github.com/thoughtbot/clearance/pull/942) to fix the docs, so I'm closing this issue.
