### ISSUE TITLE
Ruby 3.0+ support, and support for older Rails version

### ISSUE THREAD

**Issue by neilvilela** [thoughtbot/clearance#956]
Hi, everyone :wave: 

I'm trying to make sure that Clearance runs smoothly on Ruby 3.0 and 3.1, but I had some issues with testing it on Appraisal due to their compatibility with versions of Rails older than 6.0.

Checking the [Ruby/Rails compatibility table](https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html), I could see that [even Ruby 2.7 isn't fully compatible with Rails 5.2](https://github.com/rails/rails/issues/38426). The tests run and pass if I run them directly on the Ruby 6.0 appraisal, but no tests run at all if the Rails version isn't specified.

Is there any workaround for Appraisal to skip some Rails versions depending on the Ruby version. Better yet, does it make sense to find a workaround instead of dropping support for older Rails versions?

**Comment by dorianmariefr** [comment]
Fixed by https://github.com/thoughtbot/clearance/commit/dff0141f2ad4db8570e2ca1afd4f5403aa741d8f
