### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by JensDebergh** [thoughtbot/clearance#962]
Hi everyone!

I'm currently using clearance in an application I would love to upgrade to rails 7.
Due to dependencies of clearance I'm unable to upgrade.

I attempted to upgrade clearance myself using appraisal, but I'm bumping into some issues with `sprocket-rails` being extracted from rails.

Are there any plans to support rails 7?  Or can we consider clearance in maintenance mode and we should attempt to switch to devise?

**Comment by dorianmariefr** [comment]
Rails 7 is now supported and tested, I'm working on having Turbo support

https://github.com/thoughtbot/clearance/commit/dff0141f2ad4db8570e2ca1afd4f5403aa741d8f

**Comment by getbizzey** [comment]
Hi Dorian!

Thank you 🙏.

How do I buy you a beer or a coffee?
